[FE] 타이머 버그 개선
woowacourse-teams/2024-coduo pull request #169
Opened 2024-07-29 07:50 UTC by dle234

## 연관된 이슈

- closes: #158 

## 구현한 기능
타이머 버그 개선

## 상세 설명
- 경과 시간을 현재 시간(Date.now)으로 계산해서 오차 줄이기
- 계산 시간 단위 0.01초로 수정해서 애니메이션 부드럽게 수정
- 타이머 default 시간을 location 으로 받아온 시간으로 수정하기

2024-07-29 08:21 UTC, greetings1012 requested changes
수고하셨습니다! 오차와 애니메이션을 굉장히 빨리 수정해 주셨네요!
몇 가지 코멘트를 남겼으니 시간날 때 확인해주세요 ☺️

2024-07-30 02:17 UTC, anttiey requested changes
안녕하세요, 해시! 🍟

파란이 앞서 피드백을 잘 해주어서 저는 달 피드백이 몇 개 없었네요. 빠르게 타이머 개선하시느라 수고 많으셨습니다 😊

2024-07-30 02:17 UTC, anttiey commented on frontend/src/hooks/PairRoom/useTimer.ts
> +        if (newTimeLeft <= 0) {
`if - else` 문이 아닌 `early return` 을 적용할 수는 없나요?

2024-07-30 02:17 UTC, anttiey commented on frontend/src/hooks/PairRoom/useTimer.ts
> +  }, [isActive, startTime, defaultTime, onStop, timeLeft]);
혹시 이렇게 의존성 배열이 길어지게 된 이유가 있나요? 실질적으로 의존하고 있지 않은 변수는 해제해도 될 것 같은데 이 모든 변수를 의존하고 있는지 궁금합니다!

2024-07-30 15:06 UTC, dle234 commented on frontend/src/hooks/PairRoom/useTimer.ts
> +  }, [isActive, startTime, defaultTime, onStop, timeLeft]);
몇개의 의존성은 useEffect 내에서 사용만 하고 의존하고 있지는 않지만 넣어주지 않으면 리액트 훅에서 경고 메세지가 띄워져 전부 넣어주었습니다,,!! 경고메세지가 나더라도 제거해주는게 나을까요?

2024-07-30 15:08 UTC, merged