[BE] 액세스 코드 중복 검증
woowacourse-teams/2024-coduo pull request #176
Opened 2024-07-29 10:15 UTC by koust6u

## 연관된 이슈

- closes: #150 

## 구현한 기능
+ 중복된 엑세스 코드 생성 시 재 생성되도록 코드 구현
+ 해당 기능에 대한 추상화

## 상세 설명
테스트 코드 및 객체 유연성을 위해 생성 로직을 Factory로 한 단계 추상화하여 구현하였음

2024-07-29 10:17 UTC, JiHyeonL requested changes
[비상] 브랜치가 main 입니다!!

2024-07-29 11:33 UTC, JiHyeonL requested changes
공백 관련 피드백만 드렸슴니당
굿굿~~~!!
수고하셨어요👍👍

2024-07-29 13:19 UTC, reddevilmidzy requested changes
수고하셨습니다!

2024-07-29 13:19 UTC, reddevilmidzy approved these changes

2024-07-30 03:59 UTC, yechop approved these changes

2024-07-30 03:59 UTC, yechop commented on backend/src/test/java/site/coduo/pairroom/domain/AccessCodeFactoryTest.java
> +
빈줄 제거

2024-07-30 03:59 UTC, yechop commented on backend/src/test/java/site/coduo/pairroom/domain/PairNameTest.java
> +
빈줄

2024-07-30 03:59 UTC, JiHyeonL approved these changes

2024-07-30 04:45 UTC, koust6u commented on backend/src/main/java/site/coduo/pairroom/domain/accesscode/AccessCode.java
> +    private String value;
[의견] Entity 필드는 final하는 것이 올바른지 한번 같이 고민해봐도 좋을거 같습니다.

2024-07-30 05:36 UTC, merged

2024-07-30 08:17 UTC, reddevilmidzy commented on backend/src/test/java/site/coduo/pairroom/repository/PairRoomRepositoryTest.java
> +@Transactional
@DataJpaTest를 사용하다가 @SpringBootTest 와 @Transactional 로 변경하신 이유가 있나요?!

2024-07-30 11:23 UTC, koust6u commented on backend/src/test/java/site/coduo/pairroom/repository/PairRoomRepositoryTest.java
> +@Transactional
아직 정확한 이유를 발견하진 못했지만 @DataJpaTest는 jpa Dialect가 h2 에서 Mysql로 바뀌면서 CI과정에서 테스트가 깨졌습나다.