[FE] 북마크 컴포넌트 구현
woowacourse-teams/2024-coduo pull request #223
Opened 2024-08-01 07:13 UTC by dle234

## 연관된 이슈

- closes: #214 

## 구현한 기능
오픈그래프 컴포넌트 구현

## 상세 설명
- 1600px 이하
<img width="1280" alt="스크린샷 2024-08-01 오후 3 50 49" src="https://github.com/user-attachments/assets/de050608-e397-4191-b90b-a87c40452fbb">

- 1600px 이상
<img width="1280" alt="스크린샷 2024-08-01 오후 3 51 07" src="https://github.com/user-attachments/assets/9cd49c83-d2db-470f-a5a0-920f0e44439f">

- 1600px 이상, 최소 gap
<img width="1280" alt="스크린샷 2024-08-01 오후 3 51 14" src="https://github.com/user-attachments/assets/e2e7d768-35e6-40b5-a8ab-74299e4916af">

- title이 길어지면 말줄임표 사용하도록 했고, content 의 경우 최대 3줄일 경우 말줄임 표시되도록 구현했습니다.

grid 로 했더니 링크 추가할때 가운데 부터 추가가 되는데 혹시 다른 방법을 아시는 분 계실까요..?

2024-08-01 08:20 UTC, greetings1012 requested changes
수고하셨어요 ☺️
몇 가지 스타일 변경사항만 남겼으니 시간날 때 읽어주세요 🫡

2024-08-01 08:20 UTC, greetings1012 commented on frontend/src/components/common/Bookmark/Bookmark.tsx
> +  'contentcontentcontentcontecontentcontentcontentcontentcocontentcontentcontentconcontentcontentcontentcontentcontentcontentcontentconntentconntcontentcontentcontentcontent';
으악 🙀

2024-08-01 08:20 UTC, greetings1012 commented on frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.styles.ts
> +  place-items: center;
grid-auto-flow: column 를 추가하면 위부터 아이템이 추가될 거에요!

2024-08-01 08:20 UTC, greetings1012 commented on frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.styles.ts
> +  overflow-y: scroll;
이 친구도 auto로 바꿔주시면 아이템이 몇 개 없을 때는 스크롤바가 없어서 더 깔끔한 디자인이 될 것 같아요!

2024-08-02 01:25 UTC, dle234 commented on frontend/src/components/common/Bookmark/Bookmark.tsx
> +  'contentcontentcontentcontecontentcontentcontentcontentcocontentcontentcontentconcontentcontentcontentcontentcontentcontentcontentconntentconntcontentcontentcontentcontent';
ㅋㅎㅋㅎ쿠ㅜ

2024-08-02 03:46 UTC, greetings1012 approved these changes

2024-08-02 07:38 UTC, merged