[BE] 오픈그래프 추가
woowacourse-teams/2024-coduo pull request #227
Opened 2024-08-02 06:54 UTC by JiHyeonL

## 연관된 이슈

- closes: #98 

## 구현한 기능

## 상세 설명

2024-08-02 08:55 UTC, reddevilmidzy requested changes
코로나투혼 멋져요...! 수고하셨습니당 몇가지 코멘트 남겼어요 반영 부탁드려요!

2024-08-02 08:55 UTC, reddevilmidzy commented on backend/build.gradle
> +    id 'java'
build 파일에 공백이 추가된거 같습니다! 아마 자동정렬 때문인거 같은데 이부분 수정부탁드려요!

2024-08-02 08:55 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/referencelink/domain/OpenGraph.java
> +        this.image = EMPTY;
사실 EMPTY가 상수일 필요가 있을지는 의문이에요!

2024-08-02 08:55 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/referencelink/domain/Url.java
> +        } catch (IOException e) {
```
try {
} catch (final IOException e) {
}
```

여기에도 final...!

2024-08-02 08:55 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/referencelink/domain/Url.java
> +        } catch (IOException e) {
아니면 null을 리턴하지 말고 커스텀 예외를 만들어서 던지는건 어떤가요?

2024-08-02 08:55 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/referencelink/repository/OpenGraphEntity.java
> +    private String headTitle;
네이밍 좋습니다!

2024-08-02 08:55 UTC, reddevilmidzy commented on backend/src/test/java/site/coduo/acceptance/ReferenceAcceptanceTest.java
> +@Transactional
이 트랜잭셔널 애노테이션 자카르타가 제공해주는 거 말고 `import org.springframework.transaction.annotation.Transactional;` 스프링이 제공해주는 거 사용해주세요! 

둘다 트랜잭션 지원은 동일한데, 스프링 친구가 제공해주는게 기능이 더 많아요,

2024-08-02 08:55 UTC, reddevilmidzy commented on backend/src/test/java/site/coduo/acceptance/ReferenceAcceptanceTest.java
> +@Transactional
자카르타꺼 사용해도 되는데 다른 곳에선 스프링꺼 사용해서 컨벤션 맞추는 방향으로,,,

2024-08-02 08:55 UTC, reddevilmidzy commented on backend/src/test/java/site/coduo/referencelink/domain/OpenGraphTest.java
> +        Assertions.assertAll(
Assertions 은 static import 사용해주세요!

2024-08-02 08:55 UTC, reddevilmidzy commented on backend/src/test/java/site/coduo/referencelink/service/ReferenceLinkServiceTest.java
> +        Assertions.assertAll(
여기도 Assertions static import 사용해주세요!

2024-08-02 12:00 UTC, JiHyeonL commented on backend/build.gradle
> +    id 'java'
``` 
plugins {
	id 'java'
	id 'org.springframework.boot' version '3.3.1'
	id 'io.spring.dependency-management' version '1.1.5'
}
```

```
plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.1'
    id 'io.spring.dependency-management' version '1.1.5'
}
```

전자가 이전 버전이고, 후자가 지금 버전입니다
인텔리제이에서는 4칸 들여쓰기로 보이는데 왜 깃허브에서는 2칸 들여쓰기가 되어있을까요?!

2024-08-02 12:05 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/referencelink/domain/OpenGraph.java
> +        this.image = EMPTY;
보통 null을 초기화 되지 않은 값으로 사용하는데, null이 아닌 빈 문자열을 기본 값으로 사용한다는 의미로 상수화를 해 준 것 같습니다!
상수 이름이 `DEFAULT`라면 이 의미를 더 강조할 수 있을까요?

2024-08-02 12:08 UTC, JiHyeonL commented on backend/src/test/java/site/coduo/acceptance/ReferenceAcceptanceTest.java
> +@Transactional
오 감사합니다!
역시 꼼꼼한 레디 👍👍

2024-08-02 13:21 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/referencelink/domain/Url.java
> +        } catch (IOException e) {
커스텀 예외를 던져주는게 더 명시적일 것 같네요! 👍👍

2024-08-04 10:12 UTC, koust6u requested changes

2024-08-04 10:12 UTC, koust6u commented on backend/src/main/java/site/coduo/referencelink/domain/OpenGraph.java
> +    }
[컨벤션]
builder 사용시 생성자 접근제한자 private으로 막아놓기로 통일했던것으로 기억해요.
```suggestion
    @Builder
    private OpenGraph(final String headTitle,
                     final String openGraphTitle,
                     final String description,
                     final String image
    ) {
        this.headTitle = headTitle;
        this.openGraphTitle = openGraphTitle;
        this.description = description;
        this.image = image;
    }
```

2024-08-04 10:12 UTC, koust6u commented on backend/src/main/java/site/coduo/referencelink/domain/OpenGraph.java
> +            return new OpenGraph(EMPTY, EMPTY, EMPTY, EMPTY);
[의견]
빈 값이 상수일때 EMPTY라는 네이밍은 혼란을 초래할 여지가 있어보여요.
개인적으로 빈 문자열일 경우 BLANK 혹은 BLANK_XXX  이 더 와닿는것 같아요.

2024-08-04 10:12 UTC, koust6u commented on backend/src/test/java/site/coduo/referencelink/service/OpenGraphServiceTest.java
> +@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD)
헉!! 👀

2024-08-04 11:26 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/referencelink/domain/OpenGraph.java
> +            return new OpenGraph(EMPTY, EMPTY, EMPTY, EMPTY);
좋은 의견이네요!! 👍👍
잉크와 같이 이야기해보고 네이밍 수정해 보겠습니다!

2024-08-04 11:36 UTC, JiHyeonL commented on backend/src/test/java/site/coduo/referencelink/service/OpenGraphServiceTest.java
> +@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD)
헉!!
@Transactional 어노테이션을 사용해도 테스트 격리가 되지 않아 사용하게 되었는데, 
다른 방식을 찾아봐야겠네요🤣

2024-08-06 05:36 UTC, closed without merging