#18 create reference link
woowacourse-teams/2024-coduo pull request #23
Opened 2024-07-15 16:27 UTC by koust6u

## 연관된 이슈

- closes: #18 

## 구현한 기능
- [x] 레퍼런스 링크 CRUD API 구현
- [x] 레퍼런스 링크 API Swagger 문서화
- [x] 예외 사항 핸들링  

## 상세 설명
컨벤션을 살핀다고 살폈는데 처음이라 낯설어 꼼꼼한 리뷰 부탁드립니다. 
또한 서버 실행하시고 [여기](http://localhost:8080/api-docs)에 접속해서 문서화 부족한 부분도 살펴주시면 피드백 반영하겠습니다 .

2024-07-15 17:02 UTC, JiHyeonL requested changes
문서화 부분은 좀 더 읽고 코멘트 남기겠습니다!

2024-07-15 17:02 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/referencelink/service/ReferenceLinkService.java
> +    @Transactional
[질문] 클래스 단위로 transactional을 붙였는데 메서드에도 모두 transactional을 명시해준 이유가 있을까요?

2024-07-15 17:05 UTC, koust6u commented on backend/src/main/java/site/coduo/referencelink/service/dto/ReferenceLinkCreateRequest.java
> +public record ReferenceLinkCreateRequest(
[수긍] 오 좋은 의견인거 같네요. 레모네 한번 같이 토의해보아요.

2024-07-15 17:06 UTC, koust6u commented on backend/src/main/java/site/coduo/referencelink/domain/ReferenceLink.java
> +public class ReferenceLink extends BaseTimeEntity {
why?

2024-07-15 17:12 UTC, koust6u commented on backend/src/main/java/site/coduo/referencelink/domain/ReferenceLink.java
> +    }
[답변] 우리는 Entity의 id 생성에 전혀 관여할 여지 없다 생각합니다. (Entity의 Id 생성과 관리는 오로지 JPA의 몫이라는 생각)
특히, 협업하는 과정에서 생성자를 통해 굳이 개발자가 id에 접근을 할 여지를 열어두지 않고자 함이었습니다.
`감사합니다`👍

2024-07-15 17:19 UTC, reddevilmidzy approved these changes

2024-07-15 17:19 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/referencelink/controller/ReferenceLinkController.java
> +    public ResponseEntity<Void> delete(@PathVariable("id") final Long id) {
위 메서드랑 아래 메서드이 Long 타입 차이가 있습니다! 큰 의도가 없다면 통일해주면 좋을 것 같아요

2024-07-15 17:19 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/referencelink/domain/ReferenceLink.java
> +        }
만약 이런식으로 equals를 한다면 다 통일해주는게 좋을 것 같아요! 토의해보죠

2024-07-15 17:22 UTC, koust6u commented on backend/src/main/java/site/coduo/referencelink/service/ReferenceLinkService.java
> +    @Transactional
[대답] 클래스 레벨의 @Transaction(readonly=true)을  붙힌 이유를 잘 설명한 아티클일 있어 [이글](https://medium.com/@jkha7371/is-transactional-readonly-true-a-silver-bullet-1dbf130c97f8)로 답변을 대신하겠습니다.

진짜 DB 데이터를 건드는 로직에만 @Transaction을 별도로 열어두었어요 😃

2024-07-15 21:42 UTC, JiHyeonL approved these changes

2024-07-16 02:05 UTC, yechop approved these changes

2024-07-16 02:05 UTC, yechop commented on backend/src/main/java/site/coduo/referencelink/service/dto/ReferenceLinkResponse.java
> +        @Schema(description = "레퍼런스 링크", example = "https:www.//naver.com")
```suggestion
        @Schema(description = "레퍼런스 링크", example = "https://www.naver.com")
```

2024-07-16 02:16 UTC, merged

2024-07-17 03:59 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/referencelink/domain/ReferenceLink.java
> +    }
와우;; 저도 동의합니다!
이 방식으로 리팩토링 해 봐야겠어요