[FE] 페어룸 마일스톤 설정 기능 구현 및 레퍼런스 링크 오픈그래프 API 연동
woowacourse-teams/2024-coduo pull request #277
Opened 2024-08-07 11:19 UTC by anttiey

## 연관된 이슈

- closes: #238

## 구현한 기능
- 페어룸 마일스톤 설정 Drag and Drop 기능을 구현했습니다.
- 레퍼런스 링크 오픈그래프 API를 연동했습니다.
- 페어룸 페이지에 최소 너비와 최소 높이를 부여하여 화면이 작아져도 레이아웃이 깨지지 않도록 개선했습니다.

2024-08-07 11:40 UTC, dle234 approved these changes
👍 반응형 최고~~~

2024-08-08 02:58 UTC, greetings1012 requested changes
수고하셨습니다! 몇 가지 리뷰 남겼으니, 시간날 때 확인해주세요 😆

2024-08-08 02:58 UTC, greetings1012 commented on frontend/src/components/PairRoom/PairRoomCard/Header/Header.styles.ts
> +export const Layout = styled.div<{ $isOpen: boolean }>`
이 친구는 isOpen을 어디서 쓰는 건가요? 🤔

2024-08-08 02:58 UTC, greetings1012 commented on frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.tsx
> +        <PairRoomCard.Header
이 친구가 클릭이 가능하다는 걸 알 수 있는 요소가 있었으면 좋겠어요!
ex) hover 속성, cursor:pointer 등...

2024-08-08 02:58 UTC, greetings1012 commented on frontend/src/components/PairRoom/TodoListCard/TodoItem/TodoItem.tsx
> +    </S.Layout>
👍

2024-08-08 10:11 UTC, anttiey commented on frontend/src/components/PairRoom/PairRoomCard/Header/Header.styles.ts
> +export const Layout = styled.div<{ $isOpen: boolean }>`
필요 없는 `prop` 이네요! 삭제했습니다 😊

2024-08-08 10:16 UTC, greetings1012 approved these changes

2024-08-08 11:55 UTC, greetings1012 approved these changes

2024-08-08 11:57 UTC, merged