feat: ReferenceLink 검증 추가
woowacourse-teams/2024-coduo pull request #39
Opened 2024-07-18 06:21 UTC by yechop

## 연관된 이슈

- closes: #37 

## 구현한 기능

레퍼런스 링크 url 빈 값 검증 추가

## 상세 설명

2024-07-18 07:48 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/referencelink/domain/ReferenceLink.java
>      }
equals & hashcode 를 제거한 이유가 있나요?

2024-07-18 08:23 UTC, koust6u commented on backend/src/main/java/site/coduo/referencelink/domain/ReferenceLink.java
>      }
이유 없음 추가하겠습니다///

2024-07-18 08:37 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/referencelink/domain/ReferenceLink.java
>      }
캄사합니다!

2024-07-18 08:50 UTC, JiHyeonL requested changes
슛

2024-07-18 08:50 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/referencelink/repository/ReferenceLinkEntity.java
> +package site.coduo.referencelink.repository;
엔티티가 레포지토리 패키지에 있어요!!

2024-07-18 08:50 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/referencelink/repository/ReferenceLinkEntity.java
> +    private String url;
[질문] 
ReferenceLink를 url 자료형으로 사용하지 않고 생성자로 받아서 String url을 가져와서 저장하는 이유가 무엇일까요?

2024-07-19 04:36 UTC, yechop commented on backend/src/main/java/site/coduo/referencelink/repository/ReferenceLinkEntity.java
> +package site.coduo.referencelink.repository;
레퍼런스 링크를 엔티티와 도메인으로 분리했고, 엔티티는 단순 테이블로만 사용하도록 만들어 레포지토리 패키지에 넣었습니다

2024-07-19 04:41 UTC, koust6u commented on backend/src/main/java/site/coduo/referencelink/repository/ReferenceLinkEntity.java
> +    private String url;
이유1. java.net.URL 클래스 내부를 보니, protocol, host, authority 등의 부가 정보를 많이 담고 있습니다.
하지만 현재 우리 도메인에서는 단순히 사용자 레퍼런스 링크로 사용되는 문자열만이 필요하다 생각하여 직접 만들어 사용할 계획입니다.

이유2. URL 자료형이 JPA 엔티티의 속성으로 가지고 있을때 어떻게 저장되고 어떤 문제가 숨어있을지 몰르기 때문입니다.

2024-07-19 04:44 UTC, koust6u approved these changes
깔끔하게 잘 구현하셨네요. 이만 머지하겠습니다

2024-07-19 04:50 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/referencelink/repository/ReferenceLinkEntity.java
> +    private String url;
이해하였습니다👍

2024-07-19 04:51 UTC, JiHyeonL approved these changes

2024-07-19 06:09 UTC, reddevilmidzy approved these changes

2024-07-19 06:10 UTC, merged