[BE] 페어룸 상태 저장 기능 완료
woowacourse-teams/2024-coduo pull request #409
Opened 2024-08-16 05:47 UTC by JiHyeonL

## 연관된 이슈

- closes: #336 

## 구현한 기능
- 페어룸 상태 저장
- 페어룸 가장 최근 상태 조회

## 상세 설명
### 페어룸 상태 저장
상태로
  - 드라이버 이름
  - 네비게이터 이름
  - 타이머 라운드
  - 타이머 남은 시간 
 
를 저장합니다.

### 페어룸 가장 최근 상태 조회
``` java
Optional<PairRoomHistoryEntity> findTopByPairRoomIdOrderByCreatedAtDesc(long pairRoomId);
```
1. 페어룸 id에 해당하는 히스토리를 찾는다.
2. 히스토리를 생성 순서대로 내림차순 한다.
3. 첫번째 히스토리를 반환한다.
이 순서대로 페어룸 가장 최근 상태를 반환합니다.

## 변경한 기능
- 문서화 잘못된 부분이 있어 수정했습니다!

2024-08-16 06:06 UTC, reddevilmidzy requested changes

2024-08-16 06:06 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/pairroom/dto/PairRoomReadResponse.java
> +        @Schema(description = "타이머 시간. millisecond 기준으로 저장한다.", example = "60000") long timerDuration
요고 Long으로 수정해주세요

2024-08-16 06:06 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/pairroomhistory/service/PairRoomHistoryService.java
> +                        .orElseThrow(() -> new PairRoomHistoryNotFoundException("해당 페어룸의 히스토리가 존재하지 않습니다."));
예외 던지는 로직을 리포지토리에 default 메서드로 구현하는건 어떤가요?

2024-08-16 06:06 UTC, reddevilmidzy commented on backend/src/test/java/site/coduo/utils/CascadeCleaner.java
> +    public void deleteAllPairRoomCascade() {
오호 좋습니다 👍 
하지만 db 데이터 지우는게 AcceptanceFixture 에도 있어서 두 쪽에서 관리하고 있다는게 고민입니다

2024-08-16 06:08 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/pairroom/dto/PairRoomReadResponse.java
> +        @Schema(description = "타이머 시간. millisecond 기준으로 저장한다.", example = "60000") long timerDuration
감사합니다... 또 큰일날 뻔 했네요😱

2024-08-16 06:10 UTC, reddevilmidzy approved these changes

2024-08-16 06:21 UTC, koust6u approved these changes

2024-08-16 06:21 UTC, koust6u commented on backend/src/main/java/site/coduo/pairroomhistory/domain/PairRoomHistory.java
> +    }
💯

2024-08-16 07:03 UTC, yechop approved these changes

2024-08-16 07:03 UTC, yechop commented on backend/src/main/java/site/coduo/pairroomhistory/exception/PairRoomHistoryException.java
> +    public PairRoomHistoryException(final String message) {
빈 줄 넣어주세용

2024-08-16 08:28 UTC, reddevilmidzy requested changes
하고 싶은 거 다해

2024-08-18 05:54 UTC, greetings1012 approved these changes
좋은데요? (잘 모름)

2024-08-18 06:46 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/pairroomhistory/service/PairRoomHistoryService.java
> +                        .orElseThrow(() -> new PairRoomHistoryNotFoundException("해당 페어룸의 히스토리가 존재하지 않습니다."));
적용했습니다!

2024-08-18 07:27 UTC, reddevilmidzy requested changes
컨트롤러에 있는 파라미터에 @Valid 누락이 몇개 있는데 추가 부탁드려요!

2024-08-18 07:27 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/pairroom/dto/TimerDurationCreateRequest.java
> +        long timerDuration
사소한거긴 하지만 timerDuration의 타입을 Long이 아닌 long으로 잡아서 @NotNull 애노테이션이 필요없어요

2024-08-18 07:27 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/pairroomhistory/controller/PairRoomHistoryController.java
> +            @RequestBody final PairRoomHistoryCreateRequest request
PairRoomHistoryCreateRequest 에 @Valid 애노테이션을 추가해주세요! 
안그러면 애써 작성한 빈 밸리데이션 애노테이션들이 작동을 안해요 😢

2024-08-18 07:27 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/pairroomhistory/controller/PairRoomHistoryController.java
> +            @RequestBody final PairRoomHistoryUpdateRequest request
여기도 @Valid

2024-08-18 07:27 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/pairroomhistory/controller/docs/PairRoomHistoryDocs.java
> +public interface PairRoomHistoryDocs {
문서화 구웃

2024-08-18 08:07 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/pairroomhistory/controller/PairRoomHistoryController.java
> +            @RequestBody final PairRoomHistoryCreateRequest request
정말 중요한 부분인데 피드백 감사드립니다ㅎㅎㅎ

2024-08-18 08:20 UTC, reddevilmidzy approved these changes
LGTM

2024-08-18 08:22 UTC, merged