[BE] 마일스톤 TODO 아이템 CRUD API 구현
woowacourse-teams/2024-coduo pull request #428
Opened 2024-08-17 05:21 UTC by kelly6bf

## 연관된 이슈

- closes: #225 

## 구현한 기능
- 투두 CRUD
- 투두 위치 이동
- 투두 체크

## 상세 설명
아직 해결하지 못한 엣지 케이스가 남아있어 선배포후 점차 개선하겠습니다.

2024-08-17 06:01 UTC, reddevilmidzy requested changes

2024-08-17 06:01 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/todo/controller/TodoController.java
> +@RequestMapping("/api")
cors 랑 /api 프리픽스는 webconfigure로 해결해서 제거해주셔도 됩니다

2024-08-17 06:01 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/todo/controller/TodoController.java
> +public class TodoController implements TodoDocs {
해당 클래스 메서드들의 파라미터에 전체적으로 final 누락이 있네요 😢

2024-08-17 06:01 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/todo/infrastructure/repository/TodoEntity.java
> +@Table(name = "todo")
여기도 대문자로 변경해주세요

2024-08-17 06:01 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/pairroom/repository/ProdPairRoomRepository.java
> +public class ProdPairRoomRepository implements site.coduo.pairroom.service.port.PairRoomRepository {
이런식으로 구현하신 이유가 있나요?🤔

2024-08-17 06:01 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/todo/controller/TodoController.java
> +public class TodoController implements TodoDocs {
그리고 반환 타입들도 ResponseEntity로 감싸주세요

2024-08-17 06:01 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/todo/controller/TodoController.java
> +    }
삭제하거나 수정할 때 반환값이 아무것도 없으면 포스트맨으로 쏴볼때 값이 제대로 요청 들어갔는지 확인이 잘 안되어 답답함이 있더라구요, 반환값도 추가해주면 좋을 거 같아요

2024-08-17 06:01 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/todo/domain/Todo.java
> +    private final Long id;
Todo 도메인에도 id가 있고 TodoEntity에도 id가 있는데, 이러면 도메인과 엔티티를 분리하는 이유가 없어지는거 같은데 아닌가요(?)

2024-08-17 06:01 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/todo/infrastructure/repository/TodoEntity.java
> +public class TodoEntity extends BaseTimeEntity {
엔티티에는 id로 체크하는 equals & hashcode 추가부탁드려요!

2024-08-17 06:44 UTC, JiHyeonL requested changes
켈리 todo 구현하느라 수고했어요!
코드가 전체적으로 깔끔하고 생각할 거리가 많아서 리뷰하면서 많이 배워갑니다👍
피드백 몇가지 남겼으니 확인 부탁드려요!

2024-08-17 06:44 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/pairroom/repository/ProdPairRoomRepository.java
> +public class ProdPairRoomRepository implements site.coduo.pairroom.service.port.PairRoomRepository {
PairRoomRepository를 import 해주는 것은 어떨까요!

2024-08-17 06:44 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/todo/controller/request/CreateTodoRequest.java
> +}
dto 패키지 위치가 도메인마다 다른 위치에 있어서
이 부분도 팀원들과 함께 이야기 하면 좋을 것 같네요!😁

2024-08-17 06:44 UTC, JiHyeonL commented on backend/src/test/java/site/coduo/pairroom/mock/FakePairRoomRepository.java
> +            data.removeIf(item -> Objects.equals(item.getId(), pairRoom.getId()));
else는 생략해 주어도 될 것 같아요

2024-08-17 06:44 UTC, JiHyeonL commented on backend/src/test/java/site/coduo/todo/mock/FakeTodoRepository.java
> +        } else {
여기도 else 생략!

2024-08-17 06:44 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/todo/controller/TodoController.java
> +    @GetMapping("/{accessCode}/todos")
켈리의 코드를 보고 생각났는데요, 엔드포인트에서 자원을 단수로 표현할 것인지, 복수로 표현할 것인지 정해봐도 좋을 것 같아요!

관련 내용을 찾아보니 보통 복수를 사용하는데, 팀 컨벤션에 따라 단수를 사용하기도 한다고 하네요.
어떤 경우 단수를 사용하고, 복수를 사용할지 생각해 봅시다!

2024-08-17 06:44 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/todo/domain/Todo.java
> +    ) {
필드가 4개 이상일 경우 private 생성자에 builder 어노테이션을 붙여서 빌더를 사용하기로 했습니다!

2024-08-17 06:44 UTC, JiHyeonL commented on backend/src/test/java/site/coduo/todo/service/TodoServiceTest.java
> +    private TodoService todoService;
👍👍
페이크 객체를 적절하게 사용해서 테스트 하셨네요!!
저도 테스트 코드가 길어질 때가 많은데, 페이크 객체를 만들어서 사용해 봐야겠어요.

2024-08-17 07:00 UTC, kelly6bf commented on backend/src/main/java/site/coduo/todo/controller/TodoController.java
> +@RequestMapping("/api")
네! 제거하겠습니다.

2024-08-17 07:00 UTC, kelly6bf commented on backend/src/main/java/site/coduo/todo/controller/TodoController.java
> +public class TodoController implements TodoDocs {
적용하겠습니다.

2024-08-17 07:02 UTC, kelly6bf commented on backend/src/main/java/site/coduo/pairroom/repository/ProdPairRoomRepository.java
> +public class ProdPairRoomRepository implements site.coduo.pairroom.service.port.PairRoomRepository {
도메인 & Entity분리는 결국 JPA라는 외부 기술을 순수 도메인 객체에서 의존성을 분리하기 위한 목적으로 수행하는 기법입니다.

다만 기존 구현되어있던 JPA를 그대로 활용하기에는 네이밍이 겹치는 문제가 있어 우선 임의적으로 객체를 새로 만들어 사용했습니다.

이부분은 텍스트로 작성하기에는 너무 길어질거 같아 월요일 대면으로 설명드리겠습니다.

2024-08-17 07:02 UTC, kelly6bf commented on backend/src/main/java/site/coduo/todo/controller/TodoController.java
> +    }
반환값은 아이디면 좋을까요?

2024-08-17 07:03 UTC, kelly6bf commented on backend/src/main/java/site/coduo/todo/domain/Todo.java
> +    private final Long id;
위에서 언급드린것처럼 도메인 & Entity 분리는 JPA의 의존성을 분리하기 위해 수행하였고, Id 필드의 존재 이유는
- entidy -> 테이블의 PK를 표현
- domain -> 각각의 객체를 구분한 고유 값

위와 같기에 문제 없다고 생각합니다.

2024-08-17 07:03 UTC, kelly6bf commented on backend/src/main/java/site/coduo/todo/infrastructure/repository/TodoEntity.java
> +public class TodoEntity extends BaseTimeEntity {
적용하겠습니다.

2024-08-17 07:04 UTC, kelly6bf commented on backend/src/main/java/site/coduo/pairroom/repository/ProdPairRoomRepository.java
> +public class ProdPairRoomRepository implements site.coduo.pairroom.service.port.PairRoomRepository {
위 레디가 남겨주신 코멘트에 이유를 적어놨습니다. 역시 월요일 대면에서 다시금 설명드리겠습니다.

2024-08-17 07:04 UTC, kelly6bf commented on backend/src/main/java/site/coduo/todo/controller/request/CreateTodoRequest.java
> +}
좋습니다. 월요일에 얘기해보면 좋을거 같아요.

2024-08-17 07:04 UTC, kelly6bf commented on backend/src/test/java/site/coduo/pairroom/mock/FakePairRoomRepository.java
> +            data.removeIf(item -> Objects.equals(item.getId(), pairRoom.getId()));
테스트 코드에서만 사용되는 목객체여서 우선 구현 편의를 위해 else을 붙였습니다!

2024-08-17 07:04 UTC, kelly6bf commented on backend/src/main/java/site/coduo/todo/controller/TodoController.java
> +    @GetMapping("/{accessCode}/todos")
동의합니다.

2024-08-17 07:04 UTC, kelly6bf commented on backend/src/main/java/site/coduo/todo/domain/Todo.java
> +    ) {
적용하겠습니다!

2024-08-17 07:22 UTC, kelly6bf commented on backend/src/main/java/site/coduo/todo/controller/TodoController.java
> +    }
생성 컨트롤러까지는 URI를 추가하는것에 동의하지만 개인적으로 Patch는 좀 고민이 필요할거같아요. 결국 'postman'으로 직접적 요청을 보냈을 경우지 실제 클라이언트가 API를 사용할때는 정해진 애플리케이션 로직에 의해 API 호출되고 처리하기에 굳이 불필요한 메시지를 전달할 필요가 있을까 하는 의문이 들어요! (지금 프로젝트 API는 복잡도가 낮아 http status code로 표현하기 충분하고요!)

2024-08-17 07:24 UTC, kelly6bf commented on backend/src/test/java/site/coduo/todo/mock/FakeTodoRepository.java
> +        } else {
위 이유와 마찬가지입니다.

2024-08-17 07:25 UTC, kelly6bf commented on backend/src/main/java/site/coduo/todo/domain/Todo.java
> +    ) {
우선 배포가 급해서 선배포 후 일괄 적용하겠습니다! (변경 공수가 생각보나 너무 크네요...)

2024-08-17 07:27 UTC, JiHyeonL approved these changes

2024-08-18 05:54 UTC, yechop approved these changes

2024-08-18 05:55 UTC, greetings1012 approved these changes
LGTM

2024-08-18 05:57 UTC, koust6u approved these changes

2024-08-18 06:00 UTC, merged