[BE] 페어룸 상태 추가 및 상태 변경 api
woowacourse-teams/2024-coduo pull request #451
Opened 2024-08-19 13:36 UTC by JiHyeonL

## 연관된 이슈

- closes: #432 

## 구현한 기능

## 상세 설명

2024-08-19 13:47 UTC, reddevilmidzy requested changes
@transactional 누락이 있어서 rc 드려요!

2024-08-19 13:47 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/pairroom/domain/PairRoomStatus.java
> +                .orElseThrow(() -> new PairRoomStatusNotFoundException("페어룸 상태가 존재하지 않습니다."));
이렇게 매번 112 찾는 방식 말구 Map에 저장해두는 방법도 있습니다!
[참고](https://github.com/reddevilmidzy/java-chess/blob/step2/src/main/java/view/message/ErrorCodeMessage.java)

2024-08-19 13:47 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/pairroom/service/PairRoomService.java
> +    public void updatePairRoomStatus(final String accessCode, final String statusName) {
여기에 @Transactional 애노테이션 추가해주세요!

2024-08-19 13:54 UTC, koust6u requested changes

2024-08-19 13:54 UTC, koust6u commented on backend/src/main/java/site/coduo/pairroom/service/PairRoomService.java
> +            throw new InvalidAccessCodeException("accessCode가 존재하지 않거나 중복되어 페어룸 상태 변경에 실패했습니다.");
[의견.1]
해당 로직은 데이터 중심적으로 짜여 있는거 같아요. DB 와 상호작용을 통해 객체의 상태를 검증하고 있는 걸로 보입니다. 객체와 데이터의 강결합으로 보이는데, 별도의 도메인 class로 로직을 캡슐화하는거 어떨지요???

[질문.1]
JPQL로 쿼리를 날리는데, 쿼리가 날라간후 InvalidAccessCodeException이 발생하면 어떻게 되나요?

2024-08-19 14:36 UTC, koust6u requested changes
꼼꼼하게 구현해주셨군요! 다만 몇가지 질문이나 의견이 있어 RC로 남겨요 👍
코드를 보다 보니 코멘트를 좀 많이 남겼네요.  모두 답변하기 부담스러우실거 같아. 일부 반영하시고 구두로 말씀주시면 approve 드릴게용🥺

2024-08-19 14:36 UTC, koust6u commented on backend/src/main/java/site/coduo/pairroom/controller/PairRoomController.java
> +        return ResponseEntity.noContent()
[질문] 
201 에서 204로 바꾼 이유를 알고 싶습니다!

2024-08-19 14:36 UTC, koust6u commented on backend/src/main/java/site/coduo/pairroom/domain/PairRoom.java
> +                ", status=" + status +
[감탄]
레모네 꼼꼼함 💯

2024-08-19 14:36 UTC, koust6u commented on backend/src/main/java/site/coduo/pairroom/domain/PairRoomStatus.java
> +                .orElseThrow(() -> new PairRoomStatusNotFoundException("페어룸 상태가 존재하지 않습니다."));
[감탄] 
오! 하나 배워갑니다.

2024-08-19 14:36 UTC, koust6u commented on backend/src/main/java/site/coduo/pairroom/repository/PairRoomRepository.java
>      @Modifying(clearAutomatically = true, flushAutomatically = true)
[질문] 
나중에 시간 나시면 이거 설명한번 해주세요. 🙏

2024-08-19 14:36 UTC, koust6u commented on backend/src/test/java/site/coduo/acceptance/PairRoomAcceptanceTest.java
> +                .contentType(ContentType.JSON)
[동의]
상수 사용이 가독성을 높여준다 믿고있습니다.👍

2024-08-19 14:36 UTC, koust6u commented on backend/src/test/java/site/coduo/acceptance/PairRoomHistoryAcceptanceTest.java
> +                createPairRoom(new PairRoomCreateRequest("해시", "파란", PairRoomStatus.ONBOARDING.name()));
[질문] 
사소할  수 있지만, 이유가 있는지 알고 싶어 질문합니다.  CategoryAcceptanceTest에서는 아래와 같은 스타일로 하셨는데,
여기선 스타일을 변경하신 이유가 무엇인가요?

```suggestion
                createPairRoom(new PairRoomCreateRequest("해시", "파란", "ONBOARDING"));
```

2024-08-19 14:36 UTC, koust6u commented on backend/src/main/java/site/coduo/pairroom/repository/PairRoomRepository.java
> +    int updateStatusByAccessCode(@Param("accessCode") AccessCode accessCode, @Param("newStatus") PairRoomStatus newStatus);
[질문]
객체가 상태를 변경시키는 것이 아닌 JPQL로 상태를 변경시키신 이유가 궁금합니다.

[의견] 
Jpa Repository에 대한 테스트가 있으면 좋을거 같아요.  
테스트는 테스트 그자체로써의 의미도 있지만, 문서화의 의미도 있다고 봐요.   따라서 레모네가 작성하신 JPQL이 어떤 값을 반환하는지 또는 행위에 설명이 있었으면 좋겠어요. 
뿐만 아니라, Spring-data-jpa의 쿼리 메서드도 엄연히 우리가 작성한 코드의 일부라고 생각해요. 따라서 JpaRepository의 쿼리메서드도 테스트로 검증이 필요하지 않을까?라는 생각이 들어요.!!

2024-08-19 14:38 UTC, koust6u commented on backend/src/main/java/site/coduo/pairroom/repository/PairRoomRepository.java
> +    int updateStatusByAccessCode(@Param("accessCode") AccessCode accessCode, @Param("newStatus") PairRoomStatus newStatus);
[의견.1]
해당 로직은 데이터 중심적으로 짜여 있는거 같아요. DB 와 상호작용을 통해 상태를 검증하고 있는 걸로 보입니다. 이는 객체와 데이터의 강결합으로 보이는데, 별도의 도메인 class로 로직을 캡슐화하는거 어떨지요???

[의견.2]
InvalidAccessCodeException를 발생시키는 테스트 케이스는 없네요. 추가하면 어뛀까요?

[질문]
JPQL로 쿼리를 날리는데, 쿼리가 날라간후 InvalidAccessCodeException이 발생하면 어떻게 되나요?

2024-08-19 14:41 UTC, koust6u commented on backend/src/main/java/site/coduo/pairroom/service/PairRoomService.java
> +            throw new InvalidAccessCodeException("accessCode가 존재하지 않거나 중복되어 페어룸 상태 변경에 실패했습니다.");
[의견.1]
해당 로직은 데이터 중심적으로 짜여 있는거 같아요. DB 와 상호작용을 통해 상태를 검증하고 있는 걸로 보입니다. 이는 객체와 데이터의 강결합으로 보이는데, 별도의 도메인 class로 로직을 캡슐화하는거 어떨지요???

[의견.2]
InvalidAccessCodeException를 발생시키는 테스트 케이스는 없네요. 추가하면 어뛀까요?

[질문]
JPQL로 쿼리를 날리는데, 쿼리가 날라간후 InvalidAccessCodeException이 발생하면 어떻게 되나요?

2024-08-20 01:31 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/pairroom/domain/PairRoomStatus.java
> +                .orElseThrow(() -> new PairRoomStatusNotFoundException("페어룸 상태가 존재하지 않습니다."));
[감탄]
오!! 너무 좋습니다
바로 적용해 볼게요.

2024-08-20 01:38 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/pairroom/controller/PairRoomController.java
> +        return ResponseEntity.noContent()
원래 다른 용도로 사용하는 메서드가 있었는데, 그 메서드가 삭제되고 타이머 상태를 변경하는 메서드가 추가되어서 이렇게 표기된 것 같습니다!
patch의 경우 ok와 noContent 중 고민했었는데, 반환 값이 있는 read는 ok로 반환하니까 반환 값이 없는 patch는 noContent가 낫겠다 생각해서 204를 선택했습니다.

2024-08-20 01:55 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/pairroom/repository/PairRoomRepository.java
> +    int updateStatusByAccessCode(@Param("accessCode") AccessCode accessCode, @Param("newStatus") PairRoomStatus newStatus);
프람의 이야기를 듣고 생각해보니 상태를 변경한 객체를 save하는 방식이 더 좋을 것 같네요!!
그래서 해당 메서드는 지워주었습니다.
update에만 집중해서 jpql을 사용해야겠구나! 라고 생각했는데, 더티체킹을 활용하는 방식이 더 편리하고 안전한 것 같아요.
좋은 피드백 감사드립니다😆

2024-08-20 02:01 UTC, JiHyeonL commented on backend/src/test/java/site/coduo/acceptance/PairRoomHistoryAcceptanceTest.java
> +                createPairRoom(new PairRoomCreateRequest("해시", "파란", PairRoomStatus.ONBOARDING.name()));
처음에는 문자열을 넣어줬다가, 나중에 변수를 넣는 방식으로 바꿨는데 이 부분은 놓쳤네요!
꼼꼼한 피드백 감사드립니다!

2024-08-20 02:10 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/pairroom/service/PairRoomService.java
> +            throw new InvalidAccessCodeException("accessCode가 존재하지 않거나 중복되어 페어룸 상태 변경에 실패했습니다.");
[의견 1] -> 동의합니다. 그래서 더티체킹을 통해 update하는 방식으로 수정해 주었습니다!
[의견 2] -> 위 로직을 삭제하게 되어 해당 exception을 삭제해 주었습니다.

2024-08-20 03:14 UTC, koust6u commented on backend/src/main/java/site/coduo/pairroom/repository/PairRoomRepository.java
> +    int updateStatusByAccessCode(@Param("accessCode") AccessCode accessCode, @Param("newStatus") PairRoomStatus newStatus);
[질문] 
혹시 객체를 Save한다는 방식이 XXXRepository.save(entity) 이 방식을 말씀하시건가용?

2024-08-20 03:31 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/pairroom/repository/PairRoomRepository.java
>      @Modifying(clearAutomatically = true, flushAutomatically = true)
@query 어노테이션에서 jpql이나 sql을 작성할 때 insert, update, delete, ddl 쿼리를 사용하려면 @Modify를 꼭 사용해야 합니다!
@Modify 가 없으면 `InvalidJpaQueryMethodException`가 발생합니다. 

---
@Modify 안에 있는 내용은 영속성 컨텍스트와 관련된 설정입니다!
### clearAutomatically = true
- EntityManager.clear() 와 같은 역할을 합니다.
- 영속성 컨텍스트에 포함된 엔티티가 변경될 경우 이 컨텍스트가 outdated 되기 때문에 컨텍스트를 삭제해 줄 때 사용합니다.
  - 이 설정을 사용하면 다음에 db에서 엔티티를 가져올 때 변경된 데이터를 가져올 수 있습니다. (설정하지 않으면 값을 변경했음에도 변경되기 이전 값을 가져오게 됨) 

### flushAutomatically = true
- 영속성 컨텍스트에 flush 되지 않은 변경된 데이터가 있을 때, 위의 clear 과정에서 저장되지 않은 변경 내용이 삭제될 수 있습니다. 
- 이 설정을 사용하면 쿼리가 실행되기 전에 엔티티 매니저가 flush 됩니다.

2024-08-20 03:43 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/pairroom/repository/PairRoomRepository.java
> +    int updateStatusByAccessCode(@Param("accessCode") AccessCode accessCode, @Param("newStatus") PairRoomStatus newStatus);
넵!!

2024-08-20 03:49 UTC, reddevilmidzy approved these changes

2024-08-20 03:49 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/pairroom/domain/PairRoomStatus.java
> +        throw new PairRoomStatusNotFoundException("페어룸 상태가 존재하지 않습니다.");
구우웃!!!

2024-08-20 03:49 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/pairroom/repository/PairRoomRepository.java
>  }
이게 필요없어진건가요?

2024-08-20 03:51 UTC, koust6u commented on backend/src/main/java/site/coduo/pairroom/repository/PairRoomRepository.java
> +    int updateStatusByAccessCode(@Param("accessCode") AccessCode accessCode, @Param("newStatus") PairRoomStatus newStatus);
[질문] 
DirtyChecking을 통해 객체의 상태변화를 줄 수 있는데, save를 호출하는 이유가 있을까용?

2024-08-20 03:52 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/pairroom/repository/PairRoomRepository.java
>  }
넵!!

2024-08-20 04:06 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/pairroom/repository/PairRoomRepository.java
> +    int updateStatusByAccessCode(@Param("accessCode") AccessCode accessCode, @Param("newStatus") PairRoomStatus newStatus);
프람 선생님의 강의를 듣고 트랜잭션 범위 안에 있다면 save를 호출하지 않아도 update가 된다는 것을 알게 되었습니다.
감사합니다!!

2024-08-20 04:47 UTC, koust6u approved these changes
고생하셨습니다. 짝짝👏

2024-08-20 04:50 UTC, merged