[FE] 공통 Tooltip 구현
woowacourse-teams/2024-coduo pull request #452
Opened 2024-08-19 14:57 UTC by dle234

## 연관된 이슈

- closes: #348 

## 구현한 기능
공통 툴팁 구현

## 상세 설명
<img width="556" alt="image" src="https://github.com/user-attachments/assets/4c193eb3-a2b4-456c-b9c2-f515aa64432c">

<img width="493" alt="스크린샷 2024-08-19 오후 11 56 08" src="https://github.com/user-attachments/assets/4ee6d851-e23a-4abe-be0d-f85d9d05eae5">

추후 작성하도록 하겠습니다. tooltip 사용법은 노션에 업로드하겠습니당~

2024-08-20 01:34 UTC, anttiey requested changes
안녕하세요, 해시!
Tooltip 컴포넌트 잘 구현해 주셔서 감사합니다 💯💯💯 간단하게 리뷰 달았으니 확인 부탁드릴게요 🫡

2024-08-20 01:34 UTC, anttiey commented on frontend/src/components/common/Tooltip/Tooltip.styles.ts
> +export const QuestionIcon = styled(HiQuestionMarkCircle)<{ $color: string }>`
물음표 버튼 바꾸는 거 어떤가요 ߹ - ߹
- `AiFillQuestionCircle`
- `BsFillQuestionCircleFill`
- `BsQuestionCircleFill`

2024-08-20 01:34 UTC, anttiey commented on frontend/src/components/common/Tooltip/Tooltip.tsx
> +import { ReactNode } from 'react';
`Tooltip` 에 투명도 살짝 주는 거 어떤가요?

![image](https://github.com/user-attachments/assets/3487f269-3d5e-4ccf-9c3b-68d5043acfb1)
👆 이런 느낌

2024-08-20 01:34 UTC, anttiey commented on frontend/src/components/PairRoom/PairRoomCard/Header/Header.tsx
> +const Header = ({
이 부분 props가 너무 많아져서 추후에 리팩토링이 필요할 것 같네요 😅 (당장 반영하라는 이야기는 아닙니다!)

2024-08-20 03:52 UTC, dle234 commented on frontend/src/components/common/Tooltip/Tooltip.tsx
> +import { ReactNode } from 'react';
투명도를 0.9 로 주었는데, 그 이하로 주면 글씨가 명확하게 보이지 않아서 이렇게 주었습니다!

2024-08-20 08:33 UTC, greetings1012 approved these changes
파슬리가 많은 리뷰 남겨줘서 제가 드릴 말씀이 많이 없네요! approve 남기겠습니다 👍

2024-08-20 08:33 UTC, greetings1012 commented on frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.tsx
> +                message="페어프로그래밍 도중 도움이 되었던 레퍼런스 링크들을 저장해보세요 ☺️"
☺️

2024-08-20 08:33 UTC, greetings1012 commented on frontend/src/components/common/Tooltip/Tooltip.styles.ts
> +import { AiFillQuestionCircle } from 'react-icons/ai';
eslint 오류가 발생하네요 🤗

2024-08-21 04:29 UTC, anttiey commented on frontend/src/components/common/Tooltip/Tooltip.tsx
> +import { ReactNode } from 'react';
저는 0.8이 좋은 것 같아요!

2024-08-21 04:30 UTC, anttiey approved these changes

2024-08-21 06:48 UTC, merged