[BE] 카테고리 테스트 추가
woowacourse-teams/2024-coduo pull request #456
Opened 2024-08-20 04:25 UTC by reddevilmidzy

## 연관된 이슈

- closes: #440 

## 구현한 기능

서비스 테스트 및 API 테스트 추가하였습니다. 

## 상세 설명

2024-08-20 05:03 UTC, JiHyeonL approved these changes
테스트코드 추가 좋습니다!!
궁금한 점 하나 작성했어요.

2024-08-20 05:03 UTC, JiHyeonL commented on backend/src/test/java/site/coduo/referencelink/service/CategoryServiceTest.java
> +        pairRoomRepository.save(pairRoom);
페어룸 save를 두번 하시는 이유가 있을까요!

2024-08-20 05:57 UTC, koust6u requested changes
하이 레디, 테스트 코드를 집중적으로 작성하시고 단위 테스트까지 읽으시더라고요.
그래서 관련해서 남길 피드백 독서하시면서 바로바로 적용할만한 점들 몇가지만 찝어봤어요.

코드 전체적으로 변경하기엔 시간이 많이 걸릴거 같은데, 바쁘시다면 몇개만 연습삼아 리팩토링해보는건 어떨까요??

2024-08-20 05:57 UTC, koust6u commented on backend/src/test/java/site/coduo/referencelink/domain/CategoryTest.java
> +    @ValueSource(strings = {" 스프링", "스프링 ", " 스프링 ", "                    스프링 "})
[감탄] 
👏

2024-08-20 05:57 UTC, koust6u commented on backend/src/main/java/site/coduo/referencelink/domain/Category.java
>              throw new InvalidCategoryException("카테고리 길이는 " + CATEGORY_NAME_MAX_LENGTH + "자 이하여야 합니다.");
[제안]
프로젝트 코드 전반적인 일관성을 위해서 아래와 같이 바꾸는 것이 어떨까요? 
```suggestion
        if (value.trim().length() > CATEGORY_NAME_MAX_LENGTH) {
            throw new InvalidCategoryException(String.format("카테고리 길이는 %d자 이하여야 합니다."));
```

2024-08-20 05:57 UTC, koust6u commented on backend/src/test/java/site/coduo/referencelink/service/CategoryServiceTest.java
> +                ACCESS_CODE.getValue());
[참고]
단위 테스트 3장 1.4 절을 보시면 `실행 구절이 한 줄 이상인 경우를 경계하라`라는 말이 있습니다.
보통 When 구절이 한줄 이상이라면 객체 구조에 이상이 있을 수 있다고 하네요🔥

2024-08-20 05:57 UTC, koust6u commented on backend/src/test/java/site/coduo/referencelink/service/CategoryServiceTest.java
> +        //then
[오타??]
👀

2024-08-20 05:57 UTC, koust6u commented on backend/src/test/java/site/coduo/referencelink/service/CategoryServiceTest.java
> +        final CategoryCreateRequest categoryCreateRequest = new CategoryCreateRequest("자바");
[질문]
이 코드 When & Then 절 에 같이 있을까용?

2024-08-20 05:57 UTC, koust6u commented on backend/src/test/java/site/coduo/referencelink/service/CategoryServiceTest.java
> +                categoryCreateRequest)).doesNotThrowAnyException();
[참고]
검증절이 하나의 테스트 메서드에 여러개 일 경우 객체의 추상화정도가 잘못되어 있을 수도 있다고 합니다.(feat. 유닛테스트 3.1.5)

2024-08-20 05:57 UTC, koust6u commented on backend/src/test/java/site/coduo/referencelink/service/CategoryServiceTest.java
> +
[의견]
BDD 패턴(Given-when-then) 형태에서 When절에서는 검증하고자하는 대상을 명시해줘야 가독성이 좋을거 같습니다.
또한 Then은 Assert문 즉, 검증만을 하는건 어떨까요? [이 글](https://martinfowler.com/bliki/GivenWhenThen.html)을 참고해주세요.

2024-08-20 05:57 UTC, koust6u commented on backend/src/test/java/site/coduo/referencelink/service/CategoryServiceTest.java
> +        assertThatThrownBy(() -> categoryService.createCategory(ACCESS_CODE.getValue(), categoryCreateRequest))
[의견]
사소하지만, assertThatThrownBy와 assertThatCode는 함수형 인터페이스를 인자로 받아요. 그래서 저는 상태에 대한 검증이 아닌 행위에 대한 검증이라고 보는 편입니다.  근데!! 여기서 주의할 점은 내부에 별도 행위가 중첩(ACCESS_CODE.getValue())되어 있다면, 바람직한 테스트 코드라고 보기 어려울거 가탕요.
```suggestion
        final var foo = ACCESS_CODE.getValue();
        assertThatThrownBy(() -> categoryService.createCategory(foo, categoryCreateRequest))
```

2024-08-21 04:49 UTC, koust6u approved these changes

2024-08-21 04:49 UTC, koust6u commented on backend/src/main/java/site/coduo/referencelink/domain/Category.java
> +            throw new InvalidCategoryException(String.format("카테고리 길이는 %d자 이하여야 합니다."));
[Good]
👍

2024-08-21 04:49 UTC, merged