[FE] 공통 컴포넌트(헤더) 구현
woowacourse-teams/2024-coduo pull request #46
Opened 2024-07-19 15:16 UTC by greetings1012

## 연관된 이슈

- closes #32 

## 구현한 기능

공통 컴포넌트(헤더) 구현

## 상세 설명
 
figma 시안과 동일하게 헤더를 구현했습니다.
별도로 모바일 환경(최대 768px)에서는 '페어 프로그래밍이란?' 텍스트 대신 물음표 아이콘을 띄워 모바일 환경에서도 글자가 깨지거나 밀리는 현상을 방지했습니다. 😁

2024-07-20 12:55 UTC, anttiey requested changes
안녕하세요, 파란! 🟦

어쩌다 보니 남기게 된 리뷰가 많아졌는데, 대부분 사소한 네이밍 변경 위주라서 후루룩 읽어 보시면 좋을 것 같아요 ☺️

빠르게 컴포넌트 구현해 주셔서 감사드립니다! 다음 작업도 화이팅 🫡

2024-07-20 12:55 UTC, anttiey commented on frontend/src/components/common/Header/Header.stories.tsx
> +      defaultViewport: 'iphonese2',
위 `meta` 에서 viewport 파라미터를 이미 설정해 준 것으로 보이는데, 여기서 중복으로 지정해 준 이유가 있나요?

2024-07-20 12:55 UTC, anttiey commented on frontend/src/assets/index.ts
> +import logo_title from '@/assets/images/logo_title.svg';
`svg` (또는 다른 이미지 파일) 를 이렇게 index.ts 파일로 묶어서 내보낼 때는 일반적으로 `snake_case` 보다 `PascalCase` 를 사용하는데 `PascalCase` 로 통일하는 건 어떤가요?

(컨벤션 논의가 필요할 것 같습니다 🙌🏻)

2024-07-20 12:55 UTC, anttiey commented on frontend/src/components/common/Header/Header.style.ts
> +export const Container = styled.div`
이 부분이 최상위 레이아웃이라 컨벤션 상 네이밍이 `Layout` 이 되어야 할 것 같아요!

2024-07-20 12:55 UTC, anttiey commented on frontend/src/components/common/Header/Header.style.ts
> +const AnchorInteraction = styled.a`
가볍게 `Anchor` 또는 `Link` 로 네이밍 하는 건 어떤가요?

2024-07-20 12:55 UTC, anttiey commented on frontend/src/components/common/Header/Header.style.ts
> +`;
코드 가독성을 위해 `hover`, `active` 같이 설정이 따로 들어가는 경우에는 공백을 한 줄 추가해 주는 건 어떤가요?

```suggestion
  cursor: pointer;
  
  &:hover {
    opacity: 0.7;
  }
  
  &:active {
    opacity: 0.5;
  }
`;
```

2024-07-20 12:55 UTC, anttiey commented on frontend/src/components/common/Header/Header.style.ts
> +export const LogoWrapper = styled(AnchorInteraction)``;
여기는 추가된 설정이 따로 없는데, 따로 래핑해 준 이유가 있나요?

2024-07-20 12:55 UTC, anttiey commented on frontend/src/components/common/Header/Header.tsx
> +      <S.AnchorWrapper>
여러 개의 Anchor 요소를 감싸고 있으므로, `AnchorContainer` 라는 네이밍이 되어야 할 것 같아요!

2024-07-20 12:55 UTC, anttiey commented on frontend/src/components/common/Header/Header.tsx
> +            <HiQuestionMarkCircle style={{ width: '2.5rem', height: '2.5rem' }} />
인라인 스타일로 크기를 지정하기 보단, React icons에서 기본으로 제공하는 `size` prop을 활용하는 건 어떤가요?

🔗 https://tae-jun.tistory.com/3

2024-07-20 12:55 UTC, anttiey commented on frontend/src/components/common/Header/Header.tsx
> +        <S.Logo src={logo_icon_with_title} alt="logo_icon_with_title" />
저희 피그마 시안에는 제목이 없는 아이콘으로 구성되어 있는데, 제목이 있는 아이콘으로 사용하게 된 이유가 있나요?

2024-07-20 12:55 UTC, anttiey commented on frontend/tsconfig.json
> +      "@/styles/*": ["./styles/*"]
👍👍👍

2024-07-20 13:03 UTC, greetings1012 commented on frontend/.storybook/preview.tsx
> +      viewport: { defaultViewport: 'iphonese2' },
요 친구를 preview.tsx에서 parameters로 추가해 줘야지 각 스토리북에서 불러와서 사용할 수 있더라구요!
각 스토리북에서 따로 설정하지 않으면 기본적으로 responsive가 적용되고, 추가로 설정해 줄 경우에만 iphonese2가 적용돼요!

2024-07-20 13:04 UTC, greetings1012 commented on frontend/src/components/common/Header/Header.stories.tsx
> +      defaultViewport: 'iphonese2',
위 내용과 동일합니다 😁

2024-07-20 13:05 UTC, greetings1012 commented on frontend/src/assets/index.ts
> +import logo_title from '@/assets/images/logo_title.svg';
습관적으로 파일 이름과 같은 이름을 사용했는데, 생각해보니 `PascalCase`가 맞다는 생각이 드네요!
일단 `PascalCase`로 수정하고, 월요일에 만나 논의해 봅시다 🫠

2024-07-20 13:06 UTC, greetings1012 commented on frontend/src/components/common/Header/Header.style.ts
> +export const Container = styled.div`
확인했습니다!

2024-07-20 13:09 UTC, greetings1012 commented on frontend/src/components/common/Header/Header.style.ts
> +const AnchorInteraction = styled.a`
anchor에 종속되어 있는 interaction만 따로 빼놓은 스타일이다 보니, 개인적으로 변수명에서 위 스타일을 분리한 의도를 명확하게 밝히고 싶어 AnchorInteraction이라는 이름을 붙였어요!
파슬리의 생각은 어떠신가요? 🤔

2024-07-20 13:15 UTC, greetings1012 commented on frontend/src/components/common/Header/Header.style.ts
> +`;
파슬리가 추천한 방식의 가독성이 훨씬 좋네요! 수정했습니다 👍

2024-07-20 13:19 UTC, greetings1012 commented on frontend/src/components/common/Header/Header.style.ts
> +export const LogoWrapper = styled(AnchorInteraction)``;
logo는 <img>태그로 삽입되어야 하는데, 
AnchorInteraction은 <a>태그로만 지정할 수 있다 보니 
효과를 넣기 위해 logo에만 또 따로 hover와 active를 지정해주는 것은 불필요하다고 생각했어요.
그래서 이런 빈 값의 Wrapper가 하나 더 생기게 되었는데, 사실 저도 이 부분에 대해서는 고민이 되네요.

파슬리의 생각은 어떠신가요? 🤔

2024-07-20 14:09 UTC, anttiey commented on frontend/.storybook/preview.tsx
> +      viewport: { defaultViewport: 'iphonese2' },
아하 그렇군요! 💯💯💯

2024-07-20 14:11 UTC, anttiey commented on frontend/src/components/common/Header/Header.style.ts
> +const AnchorInteraction = styled.a`
그런 의미라면 좋은 것 같습니다 👍

2024-07-20 14:16 UTC, anttiey commented on frontend/src/components/common/Header/Header.style.ts
> +export const LogoWrapper = styled(AnchorInteraction)``;
태그로만 지정할 수 있다는 게, 현재 AnchorInteraction이 export 되어 있지 않아서 외부에서 사용할 수 없다는 이야기인가요? AnchorInteraction 자체를 외부에서 사용하는 방식은 어떤가요? 🤔

2024-07-20 17:13 UTC, greetings1012 commented on frontend/src/components/common/Header/Header.tsx
> +      <S.AnchorWrapper>
그렇네요! 안쪽의 `HowToPairAnchorWrapper`도 container로 수정할게요!

2024-07-20 17:14 UTC, greetings1012 commented on frontend/src/components/common/Header/Header.tsx
> +            <HiQuestionMarkCircle style={{ width: '2.5rem', height: '2.5rem' }} />
최대한 rem을 쓰려고 일부러 size를 사용하지 않았는데(size는 고정 픽셀), 이런 부분에서는 사용하는 것이 좋을까요?

2024-07-20 17:17 UTC, greetings1012 commented on frontend/src/components/common/Header/Header.tsx
> +        <S.Logo src={logo_icon_with_title} alt="logo_icon_with_title" />
헤더를 디자인하면서 보니, 다른 사이트들과 달리 헤더에 많은 정보가 없어 여백이 많이 남아 보였어요.
또한, 로고 자체에서는 웹 사이트의 정체성이 확실히 드러나지 않는 것 같아 제목이 있으면 더 좋을 것 같다는 생각을 했어요.
파슬리의 생각은 어떠신가요? 🤔

2024-07-21 01:32 UTC, anttiey commented on frontend/src/components/common/Header/Header.tsx
> +            <HiQuestionMarkCircle style={{ width: '2.5rem', height: '2.5rem' }} />
방금 React icons 공식 문서를 찾아 보니까 size 기본값이 `1em` 인 것으로 보아 상대 단위로 지정이 가능한 것 같아요! 

```js
<HiQuestionMarkCircle size="2.5rem" />
```

라이브러리에서 제공하고 있는 props가 있으므로, 인라인 스타일로 덮어씌우기 보단 이를 활용하는 게 좋다고 생각했어요. 파란의 생각은 어떤지요 👀

2024-07-21 01:39 UTC, anttiey commented on frontend/src/components/common/Header/Header.tsx
> +        <S.Logo src={logo_icon_with_title} alt="logo_icon_with_title" />
그때 피그마 디자인에서 제목이 없는 아이콘으로 구성했던 이유가 메인 페이지에서 `코딩해듀오` 라는 제목이 두 번 나타나서 그랬던 걸로 기억해서 이 부분은 내일 다같이 얘기해 보면 좋을 것 같아요 🙌🏻

2024-07-21 09:10 UTC, dle234 approved these changes
코드 잘 봤습니다!
딱히 수정할 부분이 안보여서 간단한 코멘트 남겨뒀어요 👍

2024-07-21 09:10 UTC, dle234 commented on frontend/src/components/common/Header/Header.tsx
> +          <LuHome style={{ width: '2.5rem', height: '2.5rem' }} />
아이콘 크기나 router 도 constant 로 분리해주는게 좋을 것 같아요!

2024-07-22 05:36 UTC, greetings1012 commented on frontend/src/components/common/Header/Header.style.ts
> +  @media (max-width: 768px) {
저도 그게 좋을 것 같아요! theme로 분리하겠습니다!

2024-07-22 05:45 UTC, greetings1012 commented on frontend/src/components/common/Header/Header.tsx
> +          <LuHome style={{ width: '2.5rem', height: '2.5rem' }} />
이것 또한 분리했습니다! 좋은 의견 감사해요 ☺️
앞으로는 스타일을 작성할 때 자주 쓰이는 것들은 분리하는 습관을 들여야겠네요 😃

2024-07-22 05:45 UTC, greetings1012 commented on frontend/src/components/common/Header/Header.tsx
> +        <S.Logo src={logo_icon_with_title} alt="logo_icon_with_title" />
로고만 들어있는 아이콘으로 교체했어요 😀

2024-07-22 05:49 UTC, greetings1012 commented on frontend/src/components/common/Header/Header.tsx
> +            <HiQuestionMarkCircle style={{ width: '2.5rem', height: '2.5rem' }} />
size의 경우에도 rem을 이용한 크기 설정을 지원하는군요! 하나 배워갑니다 👍
size를 통해 설정한 후 theme에 분리했어요!

2024-07-22 05:50 UTC, greetings1012 commented on frontend/src/components/common/Header/Header.style.ts
> +export const LogoWrapper = styled(AnchorInteraction)``;
layout에서 a 태그 전체에 효과를 적용하는 식으로 수정했습니다!

2024-07-22 05:59 UTC, anttiey approved these changes

2024-07-22 06:00 UTC, merged