.
woowacourse-teams/2024-coduo pull request #47
Opened 2024-07-20 07:05 UTC by dle234

## 연관된 이슈

- closes: (이슈 번호)

## 구현한 기능

## 상세 설명

2024-07-20 12:10 UTC, greetings1012 approved these changes
작동에도 전혀 문제가 없는 걸 확인했고, 기본 디자인도 아주 잘 설정해주셨다고 생각해요!
아주 사소한 코멘트 하나만 남겼습니다 ㅎㅎ
수고하셨습니다 해시! 주말 푹 쉬고 월요일에 봐요 😁

2024-07-20 12:10 UTC, greetings1012 commented on frontend/src/components/common/Button/Button.styles.tsx
> +import { ButtonColor } from './Button';
이 부분도 절대 경로로 지정해 주는 건 어떨까요!
이 친구만 상대 경로라 조금 외로워 보여요 🥲

2024-07-20 12:10 UTC, greetings1012 commented on frontend/src/components/common/Button/Button.tsx
> +  color = 'primary',
👍

2024-07-20 13:22 UTC, anttiey requested changes
안녕하세요, 해시! 🍟

컴포넌트 구현하시느라 정말 고생하셨습니다! 버튼은 특히나 바리에이션이 많은 작업이라 힘드셨을 텐데, 잘 구현해 주신 것 같아요 ㅎㅎ

몇 가지 피드백 남겼으니 확인 부탁드립니다 🌱

2024-07-20 13:22 UTC, anttiey commented on frontend/src/components/common/Button/Button.tsx
> +    <>
여기 `Fragment` 가 붙은 이유가 있나요? 없어도 정상 작동하지 않나요?

2024-07-20 13:22 UTC, anttiey commented on frontend/src/components/common/Button/Button.tsx
> +        onClick={click}
`onClick` 과 같은 기본 동작은 `ButtonHTMLAttributes<HTMLButtonElement>` 으로 props를 뚫어서 가져오는 게 좋을 것 같아요 😊 저희가 버튼을 저희가 만든 공통 컴포넌트로 대체하는 만큼, 버튼이 기본적으로 하는 일은 전부 할 수 있어야 하니까요!

<hr />

👇🏻 예시 (ButtonHTMLAttributes 활용하는 부분만 봐 주세용)
```js
import { ButtonHTMLAttributes } from 'react';
import * as S from './Button.style';

interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  content: string;
  isActive?: boolean;
  customStyle?: string;
}

function Button({ isActive = true, customStyle = '', content, ...rest }: ButtonProps) {
  return (
    <S.Layout $isActive={isActive} $customStyle={customStyle} {...rest}>
      {content}
    </S.Layout>
  );
}

export default Button;
```

2024-07-20 13:22 UTC, anttiey commented on frontend/src/components/common/Button/Button.tsx
> +        size={size}
스타일링을 위한 변수와, 일반 변수를 구분하기 위해 스타일링을 위한 변수에는 명시적으로 `$` 표시를 붙여 주는 게 어떤가요? (제가 알기로 이렇게 구분해 주지 않으면 styled-components 단에서 경고를 띄우는 것 같던데, 혹시 괜찮았나요?)

2024-07-20 13:22 UTC, anttiey commented on frontend/src/components/common/Button/Button.tsx
> +        rounded={rounded}
```suggestion
        $size={size}
        $filled={filled}
        $rounded={rounded}
```

2024-07-20 13:22 UTC, anttiey commented on frontend/src/components/common/Button/Button.tsx
> +  children: React.ReactNode;
React에서 기본적으로 children을 위한 타입을 제공하는데, `React.ReactNode` 로 지정해 준 이유가 있나요?

2024-07-20 13:22 UTC, anttiey commented on frontend/src/components/common/Button/Button.styles.tsx
> +    font-size: 1.92rem;
여기가 `1.92rem` (19px) 으로 되어 있으면 사이즈가 너무 크지 않나요...? 혹시 `theme` 에서 기본 제공하는 사이즈를 사용하지 않은 이유가 있나요?

2024-07-20 13:22 UTC, anttiey commented on frontend/src/components/common/Button/Button.tsx
> +export type ButtonColor = 'primary' | 'secondary';
이 타입들은 복수의 파일에서 사용하고 있으므로 별도 파일 (Button.type.ts) 로 빼는 게 어떤가요?

2024-07-21 08:32 UTC, dle234 commented on frontend/src/components/common/Button/Button.tsx
> +  children: React.ReactNode;
큰 이유는 없습니다.! 
click 이벤트처럼 children 도 버튼의 필수 값이라고 생각하기 때문에 강제하려고 넣어주었습니다. 
혹시 통일성을 지키고 싶으면 
```js
export type StrictPropsWithChildren<P = unknown> = P & {
  children: React.ReactNode;
};
```
처럼 util 로 만들어둘까요??

2024-07-21 08:32 UTC, dle234 commented on frontend/src/components/common/Button/Button.tsx
> +    <>
이게 ,, 전에도 지적 받은적이 있는데 습관인 것 같아요 🥹 지울게요 !

2024-07-21 08:32 UTC, dle234 commented on frontend/src/components/common/Button/Button.tsx
> +        onClick={click}
ButtonHTMLAttributes 라는게 있는지 몰랐네요 👍👍 좋은 정보 감사합니다!! 🙇

2024-07-21 08:32 UTC, dle234 commented on frontend/src/components/common/Button/Button.tsx
> +        size={size}
앗 맞아요 경고 메세지 나요!! 수정했습니다!

2024-07-21 08:32 UTC, dle234 commented on frontend/src/components/common/Button/Button.styles.tsx
> +import { ButtonColor } from './Button';
넵!!

2024-07-22 06:05 UTC, anttiey commented on frontend/src/components/common/Button/Button.tsx
> +  children: React.ReactNode;
나중에 위와 같은 공통 타입을 만들어 주는 것도 좋겠다는 생각입니다 👏

2024-07-22 06:11 UTC, merged