[BE] 페어룸 히스토리 테이블명 변경 및 미사용 컬럼 삭제
woowacourse-teams/2024-coduo pull request #500
Opened 2024-09-08 03:40 UTC by koust6u

## 연관된 이슈

- closes: #495 

## 구현한 기능
+ 페어룸 히스토리 테이블명 변경
+ 미사용 컬럼 삭제
+ 페어룸 생성 시 타이머 생성도 함께 하도록 수정
+ 페어룸 컬럼 변경 (first Pair -> Navigator, second Pair -> Driver)
+ 드라비어/내비게이터 역할 변경 API 기능 구현 

## 상세 설명

2024-09-08 04:23 UTC, reddevilmidzy requested changes
updateNavigatorWithDriver 메서드 위에 애노테이션 추가랑 todo 주석 제거 부탁드립니다! 

주말에도 수고 많으셨어요

2024-09-08 04:23 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/pairroom/repository/ProdPairRoomRepository.java
> +    // todo: 나중에 백엔드 회의 소집~~
😄

2024-09-08 04:23 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/pairroom/service/PairRoomService.java
> +        pairRoomEntity.swapNavigatorWithDriver();
updateNavigatorWithDriver 메서드 위에도 @Transactional 붙어줘야 할거 같아요 안그러면 readonly=true 로 먹혀요

2024-09-08 04:23 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/pairroom/domain/Pair.java
> +    private final PairName driver;
확실히 firstName, secondName 보다 좋아진거 같군요

2024-09-08 04:23 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/referencelink/service/ReferenceLinkService.java
> +        // todo: 의도 질문하기
어떤 의도 질문이였나요??

2024-09-08 14:24 UTC, kelly6bf approved these changes
고생하셨어요 프람! 전체적으로 컨벤션에 맞춰 잘 작성해주셨습니다! 도메인 객체와 엔티티 객체의 분리도 잘해주셨어요! 🥹

개인적으로 코드를 읽으면서 얘기해보고 싶은 내용이 생겼어요.
 ```Service```레이어 내부에서 도메인 객체와 ```Entity```객체가 산발적으로 사용되는게 괜찮을까? 라는 생각이에요.
 
저희 프로젝트 내부에서 도메인과 엔티티가 분리되면서, 엔티티는 테이블 그 자체를 나타내는 객체의 성격이 매우 강해졌어요. 따라서 테이블을 의미하는 객체인만큼 이곳저곳에서 함부로 만져서는 안되고, 이를 제어하는 역할을 ```repository```객체에게 위임해야 한다고 생각해요.

따라서 변경사항이 필요하면 기존 도메인 객체에 변경된 값을 가진 새로운 객체를 생성하게 만들어서 이를 repository에 넘기고 (JPA 표준 인터페이스는 우리의 도메인 객체를 모르기에 이를 위해 별도의 repository 추상화 및 구체화가 필요해요. 제가 슬랙에서 언급한 내용입니다.) repository가 entity에 대한 제어를 수행해야한다고 생각합니다!

그렇게 되면 service는 오직 도메인 객체와 reposiroy 객체에만 요청을 보낼 수 있고, ```Repository```레이어에 존재하는 주민인 ```Entity```는 그 내부에서 일을 처리할 수 있으니까요!

프람의 생각은 어떤가요? 이 주제를 가지고 다같이 얘기해보고 싶습니다. 작업 고생하셨어요!!

2024-09-08 14:24 UTC, kelly6bf commented on backend/src/main/java/site/coduo/pairroom/domain/Pair.java
> +    private final PairName driver;
동의합니다. 같은 타입의 변수들이 각각 뭘 의미하는지 훨씬 명확해요.

2024-09-08 14:24 UTC, kelly6bf commented on backend/src/main/java/site/coduo/pairroom/domain/PairRoom.java
> -@Entity
도메인 클래스와 엔티티 클래스를 분리하셨군요! 덕분에 이제 ```PairRoom``` 도메인 객체는 JPA와 관련된 코드없이 필요한 비즈니스 로직만 확인할 수 있어 깔끔한거 같아요. 👍

2024-09-08 14:24 UTC, kelly6bf commented on backend/src/main/java/site/coduo/pairroom/domain/accesscode/AccessCode.java
>  @RequiredArgsConstructor
```PairRoom```객체는 생성자가 코드로 존재하는데 해당 객체는 ```@RequiredArgsConstructor```로 생성자가 생략되어 있어 코드 통일이 필요할거 같아요..! (심지어 필드는 ```PairRoom```이 더 많군요..!)

2024-09-08 14:24 UTC, kelly6bf commented on backend/src/main/java/site/coduo/pairroom/repository/ProdPairRoomRepository.java
> +    // todo: 나중에 백엔드 회의 소집~~
👀

2024-09-08 14:24 UTC, kelly6bf commented on backend/src/main/java/site/coduo/pairroom/service/dto/PairRoomReadResponse.java
> +import site.coduo.pairroom.repository.PairRoomEntity;
```PairRoom``` 도메인 객체 대신 ```PairRoomEntity로 응답 DTO 값을 구성하고 있는 이유가 궁금합니다..!

Service 레이어에 존재하는 DTO 내부까지 ```repository``` 레이어의 의존성이 들어가야할 필요가 있을까 싶어요..!

2024-09-19 01:24 UTC, reddevilmidzy commented
#518 과 같이 묶겠습니당

2024-09-19 01:24 UTC, closed without merging

2024-09-19 05:41 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/referencelink/service/ReferenceLinkService.java
> +        // todo: 의도 질문하기
``` java
        if (request.categoryName() == null) {
            return referenceLinkRepository.save(new ReferenceLinkEntity(referenceLink, pairRoomEntity));
        }
        // 의도 질문하기
        final CategoryEntity categoryEntity = categoryRepository.fetchByPairRoomAndCategoryName(
                pairRoomEntity, request.categoryName());
        return referenceLinkRepository.save(new ReferenceLinkEntity(referenceLink, pairRoomEntity));
```
여기에서 `categoryRepository.fetchByPairRoomAndCategoryName` 결과를 사용하지 않는데,
왜 호출하였는지 궁금했습니다~

2024-09-19 05:43 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/pairroom/domain/accesscode/AccessCode.java
>  @RequiredArgsConstructor
`@RequiredArgsConstructor` 로 대체하였습니다!