[FE] 페어룸 투두 리스트 피드백 반영
woowacourse-teams/2024-coduo pull request #503
Opened 2024-09-10 06:32 UTC by anttiey

## 연관된 이슈

- closes: #498 

## 구현한 기능
- [x] 투두 아이템 입력창 글자 제한 추가
- [x] 투두 아이템 총 개수 표시 추가
- [x] 투두 아이템을 체크했을 때 취소선이 생기도록 추가
- [x] 투두 아이템을 여러 개 작성하기 편하도록 커서 이동 추가

## 상세 설명
- 투두 아이템 입력창에 100자 글자 제한을 추가했습니다.
- 투두 아이템을 체크했을 때 취소선이 생기도록 추가하고, 체크된 투두 아이템을 더 잘 드러내기 위해 배경색을 변경했습니다.
- 투두 리스트를 여러 개 작성하기 편하도록 `투두 추가하기` 버튼을 누르면 바깥 영역을 클릭하거나 `취소` 버튼을 클릭하지 않는 한 입력창에 포커스가 남아 있도록 변경했습니다.
- Tooltip 컴포넌트를 개선했습니다.
- 페어룸 내 세부적인 UI 깨짐 현상을 개선했습니다.

2024-09-14 16:55 UTC, greetings1012 requested changes
정말 수고 많으셨습니다!
리뷰 몇 개 남겨놓았으니, 시간 날 때 확인해주세요!

2024-09-14 16:55 UTC, greetings1012 commented on frontend/src/components/PairRoom/TimerCard/TimerCard.tsx
> +  // }, []);
여기 코드를 주석으로 남겨둔 이유가 있나요? 🤔

2024-09-14 16:55 UTC, greetings1012 commented on frontend/src/components/PairRoom/TodoListCard/TodoItem/TodoItem.styles.ts
> +        : theme.color.secondary[100]};
👍

2024-09-14 16:55 UTC, greetings1012 commented on frontend/src/components/PairRoom/TodoListCard/TodoListCard.tsx
> +                <Input $css={S.inputStyles} value={value} onChange={handleChange} maxLength={100} />
최대 길이로 todo를 입력하면 todo 길이가 늘어나서 UI 일부가 화면 밖으로 나가게 되는 이슈가 있어요 😂
maxlength를 조금 줄이거나 maxwidth를 설정하면 좋을 것 같아요!

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/e2f4932c-4949-470f-8da0-eb3518c47f09">

2024-09-14 16:55 UTC, greetings1012 commented on frontend/src/components/PairRoom/ReferenceCard/Header/Header.tsx
> +        >
툴팁의 위치를 Header 제목 옆으로 바꾸는 것은 어떻게 생각하시나요?
툴팁과 설명하는 대상이 멀리 떨어져있다 보니 어떤 것에 대한 설명인지 조금 직관성이 떨어질 수도 있겠다는 생각이 들어서요 😢

2024-09-16 11:09 UTC, dle234 reviewed
고생하셨어요! 카테고리, 툴팁 부분도 같이 리팩토링 해주셔서 감사합니다~~~
+)추가로 투두 Content 를 클릭했을 때 해당 투두가 복사되거나 체크되었으면 좋겠어요. 
++) 복사는 나중에 마크다운 복사로 바뀌는걸 생각하면 개인적으로 체크 되는게 더 좋을 것 같아요 !

2024-09-16 11:09 UTC, dle234 commented on frontend/src/components/PairRoom/ReferenceCard/CategoryModal/CategoryModal.styles.ts
> +`;
👍

2024-09-16 11:09 UTC, dle234 commented on frontend/src/components/PairRoom/TimerCard/TimerCard.tsx
> +  // useEffect(() => {
이 부분 제거한 이유가 궁금합니다!

2024-09-16 11:09 UTC, dle234 commented on frontend/src/components/PairRoom/TodoListCard/TodoItem/TodoItem.styles.ts
>    transition: background 0.2s ease;
투두리스트 체크 했을 때 변하는 속도가 조금 느린 것 같아서 0.1초 정도로 줘도 좋을 것 같아요!

2024-09-16 11:09 UTC, dle234 commented on frontend/src/components/PairRoom/TodoListCard/TodoListCard.tsx
> +  useClickOutside(footerRef, () => setIsFooterOpen(false));
이 부분을 빼거나 todo 삭제 혹은 복사 했을 때 footer 가 닫히지 않도록 하면 좋을 것 같아요!

2024-09-16 11:09 UTC, dle234 commented on frontend/src/components/PairRoom/TodoListCard/TodoListCard.tsx
> +                <Input $css={S.inputStyles} value={value} onChange={handleChange} maxLength={100} />
<img width="540" alt="image" src="https://github.com/user-attachments/assets/e13be65a-4180-4f7a-96fd-214135fb4948">

<img width="670" alt="image" src="https://github.com/user-attachments/assets/02ab79ed-7a6f-4973-84fa-bac59f6133e6">

한국어는 줄바꿈이 잘 되는데 영어가 안돼서 Layout 에   word-break: break-all; 추가해주면 좋을 것 같아요 !

2024-09-17 10:35 UTC, anttiey commented on frontend/src/components/PairRoom/TimerCard/TimerCard.tsx
> +  // }, []);
이 부분 때문에 페어룸 내에서 변경 사항이 생길 때마다 팝업이 표시되어서 개발 편의성을 위해 주석 처리를 해두었는데 커밋에 들어갔네요 😅

2024-09-17 10:35 UTC, anttiey commented on frontend/src/components/PairRoom/TodoListCard/TodoListCard.tsx
> +                <Input $css={S.inputStyles} value={value} onChange={handleChange} maxLength={100} />
확인했습니다! 🚀

2024-09-17 10:38 UTC, anttiey commented on frontend/src/components/PairRoom/TimerCard/TimerCard.tsx
> +  // useEffect(() => {
페어룸 내에서 변경 사항이 생길 때마다 팝업이 표시되어서 개발 편의성을 위해 주석 처리를 해둔 부분입니다! 다시 돌려 놓도록 하겠습니다 🫡

2024-09-17 10:47 UTC, anttiey commented on frontend/src/components/PairRoom/TodoListCard/TodoListCard.tsx
> +  useClickOutside(footerRef, () => setIsFooterOpen(false));
해당 기능을 추가하게 된 건 사용자가 투두 아이템을 여러 개 작성할 때를 고려해서인데, 투두 아이템을 복사하거나, 투두 아이템을 삭제하는 건 별개의 작업이라고 생각했어요. 그리고 해당 기능을 제거하면 한 번 `투두 추가하기` 버튼을 누른 후에 푸터가 영원히 닫히지 않게 되는데, 이 부분에 대해서 해시의 의견이 궁금합니다!

2024-09-17 12:40 UTC, anttiey commented on frontend/src/components/PairRoom/ReferenceCard/Header/Header.tsx
> +        >
반영했습니다! 🚀

2024-09-17 12:41 UTC, anttiey commented on frontend/src/components/PairRoom/TodoListCard/TodoItem/TodoItem.styles.ts
>    transition: background 0.2s ease;
반영했습니다! 🚀

2024-09-19 01:44 UTC, dle234 commented on frontend/src/components/PairRoom/TodoListCard/TodoListCard.tsx
> +  useClickOutside(footerRef, () => setIsFooterOpen(false));
저는 사용자가 닫기 버튼을 누르지 않으면 영원히 닫히지 않는게 맞다고 생각해요! 저도 투두를 복사하거나 삭제하는게 별개의 작업이라고 생각하는데, 오히려 그래서 삭제나 복사 시 관계 없는 푸터가 닫히게 되면 사용자에게 예상치 못한 경험을 주는 거라고 생각해요. 그래서 사용자가 원할때 푸터가 닫히는게 더 사용성이 좋다고 느꼈습니다
이건 개인적인 의견이라 다른 크루들한테도 물어보면 좋을 것 같아요!

2024-09-19 04:09 UTC, dle234 approved these changes
👍

2024-09-19 06:21 UTC, greetings1012 approved these changes

2024-09-19 06:24 UTC, merged