[FE] 폰트 로딩 최적화
woowacourse-teams/2024-coduo pull request #517
Opened 2024-09-16 12:42 UTC by greetings1012

## 연관된 이슈

- closes: #513 

## 구현한 기능

폰트 로딩을 최적화하고 noscript 태그를 작성해 접근성을 향상했습니다.

## 상세 설명

로컬 font 파일을 삭제하고 pretendard에서 제공하는 가변 글꼴 서브셋 api를 호출해 사용하는 폰트만 불러오도록 했습니다.
또한 preconnect와 onload를 적용해 폰트의 로딩 및 적용을 최적화했습니다.

### 개선 전
<img width="1084" alt="Screenshot 2024-09-16 at 9 36 26 PM" src="https://github.com/user-attachments/assets/b0e919ed-e320-4d96-b025-1151c5e13c8b">

### 개선 후
<img width="1087" alt="Screenshot 2024-09-16 at 9 37 14 PM" src="https://github.com/user-attachments/assets/e5249dfe-6ab2-4e29-95e1-251e01a97646">

2024-09-18 06:00 UTC, anttiey requested changes

2024-09-18 06:00 UTC, anttiey commented on frontend/src/components/common/Fallback/PageFallback/PageFallback.tsx
> +      <S.Title>잠시만 기다려주세요 ☺️</S.Title>
`페이지를 불러오는 중입니다` 와 같이 조금 더 명확한 동작이 표현되는 문구는 어떤가요?

2024-09-18 06:00 UTC, anttiey commented on frontend/src/components/common/Fallback/PageFallback/PageFallback.tsx
> +const PageFallback = () => {
해당 컴포넌트는 `pages` 폴더 아래로 가야 할 거 같은데 어떻게 생각하시나요? (이름도 `Fallback` 혹은 `FallbackPage` 가 나을 거 같아요)

2024-09-18 06:00 UTC, anttiey commented on frontend/public/index.html
> +    />
오 이렇게 불러와도 `FOIT` 이나 `FOUT` 현상이 발생하지 않나요?

2024-09-18 06:00 UTC, anttiey commented on frontend/public/index.html
> +    />
| 개선 전 | 개선 후 |
|---------|---------|
| <img width="436" alt="스크린샷 2024-09-18 오후 2 50 32" src="https://github.com/user-attachments/assets/39862587-46b5-4c3e-b949-b094b62eb4f7"> | <img width="412" alt="스크린샷 2024-09-18 오후 2 50 25" src="https://github.com/user-attachments/assets/97952b55-b1b3-49ff-acc2-157645a98e8a"> |

개선하면서 어딘가 `font-weight` 이 잘못 적용되고 있는 거 같은데 이 부분 확인 가능한가요?

2024-09-18 06:00 UTC, anttiey commented on frontend/public/index.html
> +    <link rel="icon" type="image/svg+xml" href="favicon.svg" />
👏👏👏

2024-09-18 06:00 UTC, anttiey commented on frontend/webpack.production.config.js
> +      release: 'Coduo' + process.env.REACT_APP_VERSION,
이 코드는 무슨 동작을 하나요?

2024-09-18 06:00 UTC, anttiey commented on frontend/webpack.production.config.js
> +        test: /\.(png|svg|jpg|gif|mp3)$/,
이 부분 `asset/resource` 로 대체하는 건 어떨까요? `asset/resource` 가 Webpack v5에서 `file-loader` 를 대체하기 위해 나온 최신 기술이라고 하더라고요!

2024-09-18 06:00 UTC, anttiey commented on frontend/webpack.production.config.js
> +      },
저희가 CSS-in-JS 라이브러리를 사용하고 있어서 빌드 시 css 파일이 거의 생성되지 않을 거 같은데, 유의미한 성능 변화가 있었나요?

2024-09-19 02:13 UTC, dle234 reviewed
👍 고생하셨어요~~~성능 개선이 많이 되었네요!
궁금한 점 몇개 있어서 질문 남겼어요!

2024-09-19 02:13 UTC, dle234 commented on frontend/package.json
> -    "react-icons": "^5.2.1",
아이콘 버전을 올린 이유가 있을까요?

2024-09-19 02:13 UTC, dle234 commented on frontend/public/index.html
> +    <link rel="icon" type="image/svg+xml" href="favicon.svg" />
👍👍👍👍

2024-09-19 02:13 UTC, dle234 commented on frontend/webpack.production.config.js
> +      },
저도 궁금합니다!!

2024-09-19 02:13 UTC, dle234 commented on frontend/webpack.production.config.js
> +        test: /\.(png|svg|jpg|gif|mp3)$/,
오 이건 처음 봐요 👍
file-loader 부분은 dev , pro 랑 같은 것 같은데 common 에 두지 않고 분리한 이유가 있을까요?

2024-09-19 02:40 UTC, greetings1012 commented on frontend/public/index.html
> +    />
x6 slowdown에 network를 3G로 설정해도 FOIT 이나 FOUT 현상은 일어나지 않더라구요!

2024-09-19 02:44 UTC, greetings1012 commented on frontend/webpack.production.config.js
> +      release: 'Coduo' + process.env.REACT_APP_VERSION,
sentry에서 release 버전 이름을 랜덤 난수로 지정하고 있는데, 이를 Coduo + 버전으로 관리하기 위해 추가했어요!
배포 후 다시 확인해봐야 할 것 같아요 🤔

2024-09-19 02:46 UTC, greetings1012 commented on frontend/package.json
> -    "react-icons": "^5.2.1",
트리 쉐이킹을 위해 react-icons/all-files를 적용하는 과정에서 지웠다 깔았다 하면서 업데이트됐어요 😂
저희가 사용하는 아이콘 중에 react-icons/all-files에 없는 아이콘이 많아 적용에는 실패했습니다..
그래도 원래는 빌드 과정에서 쉐이킹되는 것이 정상이니까 한번 정식 배포 후 다시 테스트해보려고 해요!

2024-09-19 02:47 UTC, greetings1012 commented on frontend/src/components/common/Fallback/PageFallback/PageFallback.tsx
> +      <S.Title>잠시만 기다려주세요 ☺️</S.Title>
수정했습니다!

2024-09-19 03:13 UTC, greetings1012 commented on frontend/public/index.html
> +    />
font 이름이 `Pretendard` -> `Pretendart Variable`로 변경되었는데 font.css에서 수정되지 않아 생긴 오류였어요!
수정했습니다 😁

2024-09-19 03:28 UTC, greetings1012 commented on frontend/webpack.production.config.js
> +        test: /\.(png|svg|jpg|gif|mp3)$/,
asset/resource를 적용했습니다!
file-loader를 완전히 삭제해도 정상적으로 동작하네요!
또한 리소스 로딩 rule을 common으로 통일했습니다 👍

2024-09-19 04:46 UTC, greetings1012 commented on frontend/src/components/common/Fallback/PageFallback/PageFallback.tsx
> +const PageFallback = () => {
Loading으로 이름 수정 후 pages 폴더로 옮겼습니다!

2024-09-19 04:47 UTC, greetings1012 commented on frontend/webpack.production.config.js
> +      },
폰트를 css로 불러오게 되어 적용해 보았는데, 변화는 미미하네요 😭
다시 원상복구 시켰습니다!

2024-09-19 04:52 UTC, dle234 approved these changes

2024-09-19 05:47 UTC, anttiey approved these changes

2024-09-19 05:58 UTC, merged