Input 컴포넌트 구현
woowacourse-teams/2024-coduo pull request #52
Opened 2024-07-22 06:42 UTC by dle234

## 연관된 이슈

- closes: #34 

## 구현한 기능
Input 컴포넌트 구현

## 상세 설명

2024-07-22 07:24 UTC, anttiey requested changes
안녕하세요, 해시! 🍟

두 개의 공통 컴포넌트 구현하시느라 정말 고생 많으셨습니다 ㅎㅎ 우선적으로 보이는 것부터 리뷰 달아 봤으니 천천히 확인해 주세요 😊

2024-07-22 07:24 UTC, anttiey commented on frontend/src/components/common/Input/Input.tsx
> +Input.displayName = 'InputComponent';
혹시 이건 어떤 코드인지 알 수 있을까요? 🤔

2024-07-22 07:24 UTC, anttiey commented on frontend/src/components/common/Input/Input.tsx
> +  ): JSX.Element => {
`JSX.Element` 반환 타입이 없어도 충분히 타입스크립트에서 타입을 추론 가능할 것 같습니다.
```suggestion
  ({ width = '80%', height = '4.8rem', status = 'default', message, id, label, ...props }: InputProps, ref) => {
```

2024-07-22 07:24 UTC, anttiey commented on frontend/src/components/common/Input/Input.tsx
> +  id: string;
기본 Input props에 존재하는 값들은 커스텀해서 넣어줄 필요 없이 그대로 활용하는 게 좋을 것 같아요 😊 (props 중복 이슈)

```js
 <S.Layout>
   <S.Label htmlFor={props.id}>{label}</S.Label>
   <S.Input ref={ref} $width={width} $height={height} $status={status} {...props} />
   {message && <S.Message $status={status}>{message}</S.Message>}
</S.Layout>
```

2024-07-22 07:24 UTC, anttiey commented on frontend/src/components/common/Input/Input.tsx
> +    { width = '80%', height = '4.8rem', status = 'default', message, id, label, ...props }: InputProps,
width 기본 값은 `100%` 어떤가요? `100%` 를 제일 많이 사용하게 될 것 같아서요 🙌🏻

2024-07-22 07:24 UTC, anttiey commented on frontend/src/components/common/Input/Input.tsx
> +        <S.Input ref={ref} id={id} $width={width} $height={height} $status={status} {...props} />
혹시 이 `Input` 을 사용하려면 `ref` 를 필수적으로 전달해야 하는 건가요? `ref` 를 전달하지 않고 사용할 수도 있나요? 잘 몰라서 질문해 봅니다!

2024-07-22 07:51 UTC, dle234 commented on frontend/src/components/common/Input/Input.tsx
> +    { width = '80%', height = '4.8rem', status = 'default', message, id, label, ...props }: InputProps,
너무 길어서 80% 로 했는데 생각해보니 그건 사용자가 알아서 외부 width,padding 을 조절하겠네요! 수정했습니다!

2024-07-22 07:51 UTC, dle234 commented on frontend/src/components/common/Input/Input.tsx
> +        <S.Input ref={ref} id={id} $width={width} $height={height} $status={status} {...props} />
ref 없어도 사용 가능합니다! 혹시 나중에 입력값 입력 시 focus 조절을 해주기 위해서 추가해놨습니다!

2024-07-22 07:51 UTC, dle234 commented on frontend/src/components/common/Input/Input.tsx
> +Input.displayName = 'InputComponent';
fowardRef 를 사용했을때 displayName 을 설정해주거나 내부에서 이름 있는 함수를 넘겨줘야 하는데 저희는 화살표함수를 사용해서 displayName 을 설정해줬습니다!

2024-07-22 10:15 UTC, greetings1012 requested changes
해시! 코드를 깔끔하게 잘 작성해주셔서 많이 작성할 내용이 없네요!
사소하게 코멘트 남겼습니다 😄

2024-07-22 10:32 UTC, dle234 commented on frontend/src/components/common/Input/Input.tsx
> +  $css?: ReturnType<typeof css>;
input 은 커스텀이 많이 안들어가서 css 를 넣어줄 필요가 없을 것 같네요! 수정했습니다~~

2024-07-23 01:53 UTC, anttiey approved these changes

2024-07-23 02:47 UTC, greetings1012 approved these changes

2024-07-23 04:58 UTC, merged