[BE] 마일스톤 투두 기능에서 발생하는 에러 탐색 및 조치
woowacourse-teams/2024-coduo pull request #530
Opened 2024-09-19 08:54 UTC by kelly6bf

## 연관된 이슈

- closes: #501 

## 구현한 기능
- 투두 정렬 값 자료형을 ```Double```로 변경
- 투두 정렬 값 음수 허용
- 투두 사잇값을 더 큰수로 증가
- 부족한 검증 로직 및 테스트 추가
- 팀 컨벤션에 맞춰 JPARepository를 Service에서 사용하도록 프로덕션 로직 및 테스토 코드 변경

## 상세 설명
- 투두의 잦은 순서 변경시 예외 상황이 발생하지 않도록 정렬값 자료형을 소수 및 음수 허용으로 변경하였습니다.
- 팀 컨벤션에 맞춰 Repository / Service 및 테스트 코드를 변경하였습니다.

2024-09-19 08:55 UTC, kelly6bf commented
지금 요청드린거 테이블 컬럼 자료형이 변경되서 이대로 배포하면 에러 터집니다.. 프람도 테이블 자료형 문제 있던데 같이 작업해서 배포해야할거 같아요!

2024-09-20 06:18 UTC, reddevilmidzy commented
컨플릭트가 많이 나는군요 😥
리졸브 하고 다시 올려주세요..!

2024-09-20 11:52 UTC, JiHyeonL requested changes
켈리 수고하셨습니다!
conflict 해결한 레디도 수고하셨습니다~~

제가 슉슉 바꾼 부분이 있는데요,
TodoEntity의 PairRoom 속성의 컬럼명을
`PAIR_ROOM` -> `PAIR_ROOM_ID`로 수정해 주었습니다.

현재 컨트롤러&dto 문서화가 되어있지 않고,
ExceptionHandler에 예외 핸들링이 가장 상위 `TodoException` 만 되어있는 상태네요.

문서화와 예외 핸들링 부분만 추가해주시면 좋을 것 같습니다!

2024-09-20 11:52 UTC, JiHyeonL commented on backend/src/test/java/site/coduo/referencelink/service/ReferenceLinkServiceTest.java
> +                site.coduo.pairroom.repository.PairRoomEntity.from(INK_REDDDY_ROOM));
static import를 하지 않은 이유가 있을까요?😲

2024-09-20 11:52 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/todo/repository/TodoRepository.java
>      List<TodoEntity> findAllByPairRoomEntityOrderBySortAsc(PairRoomEntity pairRoomEntity);
오 pairRoomId로 찾는 것이 아니라 엔티티로 찾는 방법도 좋네요! 👍

2024-09-25 06:42 UTC, JiHyeonL approved these changes
와우~~~ 수고하셨습니다!
호옥시 시간 되신다면 `TodoExceptionHandler` 에 예외 핸들링 추가해주시면 좋을것같아요!

2024-09-25 06:42 UTC, JiHyeonL commented on backend/src/test/java/site/coduo/acceptance/PairRoomAcceptanceTest.java
> +//                .all()
여기까지 생성 로그 
뭐야~~~~

2024-09-25 06:52 UTC, yechop approved these changes
사소한 코멘트 하나라서 어프루브할게요

2024-09-25 06:52 UTC, yechop commented on backend/src/main/java/site/coduo/todo/controller/docs/TodoDocs.java
>  public interface TodoDocs {
docs엔 final 빼도 될것같습니다

2024-09-25 07:19 UTC, merged