[BE] 페어룸 GET api & 타이머 UPDATE api 변경
woowacourse-teams/2024-coduo pull request #539
Opened 2024-09-20 08:28 UTC by JiHyeonL

## 연관된 이슈

- closes: #535 

## 구현한 기능
### 페어룸 GET api 변경
- 문제 상황: 페어룸에 입장할 때, 페어룸 GET 요청과 타이머 GET 요청을 따로 보내야 했습니다.
- 해결: 페어룸 GET 응답으로 타이머 시간, 타이머 남은 시간을 함께 보내주었습니다.

### 타이머 UPDATE api 변경
- 문제 상황: 타이머 시간은 타이머가 한바퀴 돌았을 때만 수정 가능합니다. 그럼 타이머 남은 시간도 당연히 새로운 타이머 시간으로 update 해야합니다. 현재 타이머 시간 update api 와 타이머 남은 시간 update api가 따로 분리되어 있어 api 호출을 두번 해야 합니다. 
- 해결: 타이머 update api로 두 api 를 병합하였습니다.
---
- 문서화 & 테스트 수정 완료하였습니다.

2024-09-22 12:11 UTC, reddevilmidzy approved these changes
수고 많으셨습니다ㅏ!!

2024-09-22 12:11 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/pairroom/service/PairRoomService.java
> +        final PairRoomEntity entity = pairRoomRepository.fetchByAccessCode(accessCode);
구웃!

2024-09-22 12:11 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/pairroom/service/dto/PairRoomReadResponse.java
> +        long remainingTime
오오 기준도 추가해주셨네요 !! (_ _) 👍

2024-09-24 04:25 UTC, yechop approved these changes
구욷

2024-09-24 04:27 UTC, kelly6bf requested changes
레모네! 구현 잘 해주셨네요! 고생 많으셨습니다! ```@Transactional```관련한 부분은 팀 논의가 필요한 부분이니 우선 Approve 드릴게요!

2024-09-24 04:27 UTC, kelly6bf commented on backend/src/test/java/site/coduo/timer/service/TimerServiceTest.java
>  @Transactional
테스트 데이터를 @Transactional로 초기화할지에 대해서 팀 논의가 필요할거 같습니다!

2024-09-24 04:27 UTC, kelly6bf approved these changes

2024-09-24 04:28 UTC, JiHyeonL commented on backend/src/test/java/site/coduo/timer/service/TimerServiceTest.java
>  @Transactional
넵!! 나중에 같이 이야기해봐요!

2024-09-24 04:30 UTC, merged