[BE] 나의 페어룸 조회 기능 구현
woowacourse-teams/2024-coduo pull request #540
Opened 2024-09-22 12:30 UTC by reddevilmidzy

## 연관된 이슈

- closes: #507 

## 구현한 기능

## 상세 설명

로그인한 유저는 자신이 참여한 페어룸을 확인할 수 있는 API를 구현하였습니다.

초기에 저희가 설계한 PairRoom과 Member는 하나의 Member가 여러개의 PairRoom을 만들 수 있는 형태였습니다.  pairRoom -> member는 ManyToOne관계였는데 생각해보니 하나의 pairRoom을 한명의 member만 사용하는 것이 아니었습니다. 페어가 pairRoom을 공유하기 때문에 pairRoom과 member는 사실 다대다 관계였는데요, 그래서 둘 사이를 잇는 중간 테이블을 만들었습니다.

2024-09-22 14:40 UTC, JiHyeonL requested changes
레디, 잉크 구현하시느라 수고하셨습니다~~~

- PariRoomMemberEntity 도메인 / 엔티티 분리
- PairRoomMemberController, dto 문서화

부분을 중심으로 보완해 주시면 좋을 것 같습니다!!

+) 그리고 테스트를 돌려 보았는데, MemberServicveTest와 SseAcceptanceTest 가 터지고 있네욥 
뭐가 문제인지 같이 찾아봅시다!

2024-09-22 14:40 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/pairroom/controller/PairRoomController.java
> +        return new PairRoomCreateResponse(pairRoomService.saveNonMemberPairRoom(request));
로그인 된 사용자와 비로그인 사용자를 구분해서 페어룸을 저장해 주셨군요!
좋습니다 👍👍

2024-09-22 14:40 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/pairroommember/controller/PairRoomMemberController.java
> +public class PairRoomMemberController {
문서화를 추가해 주세요!

2024-09-22 14:40 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/pairroommember/repository/PairRoomMemberEntity.java
> +public class PairRoomMemberEntity {
PairRoomMemberEntity도 엔티티와 도메인을 분리해 주시면 좋을 것 같아요이

2024-09-22 14:40 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/pairroommember/repository/PairRoomMemberEntity.java
> +    private Member member;
각 필드의 컬럼명을 명시해 주는 것은 어떨까요!

2024-09-22 14:40 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/pairroommember/repository/PairRoomMemberEntity.java
> +    private Member member;
헉 지금보니 Member 도 도메인/엔티티 분리가 되어 있지 않군용
이건 프람에게 맞기도록 할까요?ㅋㅋㅋㅎㅎ

2024-09-22 14:40 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/pairroommember/service/PairRoomMemberService.java
> +
공백을 지워주세요!!

2024-09-22 14:40 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/pairroommember/service/dto/PairRoomMemberResponse.java
> +) {
```suggestion
public record PairRoomMemberResponse(
        Long id,
        String status,
        String navigator,
        String driver,
        String accessCode
) {
```
id도 들여쓰기를 해주는 것은 어떨까요?!
문서화도  추가해 주세요!

2024-09-22 14:40 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/pairroommember/service/dto/PairRoomMemberResponse.java
> +
공백공백

2024-09-22 14:40 UTC, JiHyeonL commented on backend/src/test/java/site/coduo/utils/CascadeCleaner.java
> +        pairRoomMemberRepository.deleteAll();
꼼꼼하시군요 😎

2024-09-22 14:40 UTC, JiHyeonL commented on backend/src/test/java/site/coduo/pairroommember/service/PairRoomMemberServiceTest.java
> +
공백공백

2024-09-22 14:40 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/pairroommember/controller/PairRoomMemberController.java
> +    public ResponseEntity<List<PairRoomMemberResponse>> getPairRooms(@CookieValue(SIGN_IN_COOKIE_NAME) String token) {
final 누락!!

2024-09-22 14:40 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/pairroom/controller/PairRoomController.java
> +            @CookieValue(value = SIGN_IN_COOKIE_NAME, required = false) String token
final 누락!!

2024-09-22 15:08 UTC, reddevilmidzy commented
@JiHyeonL 어라 테스트가 실패할리가 없을텐데요...?ㅠ🥺
푸시 하기전에 한번 확인했고 ci도 안터진거 같은데 한번 다시 확인해주실수 있나요..?!

다른 피드백 주신 부분들은 월욜에 가서 반영하겠습니다💪💪 감사합니당

2024-09-22 15:18 UTC, JiHyeonL reviewed
<img width="1252" alt="image" src="https://github.com/user-attachments/assets/acc43e60-2f5b-4d59-9550-f53cdd83246b">
이렇게 에러가 났어요!

ci는 잘 돌아갔는데 왜 테스트가 터졌는지는 모르겠슴다...

AcceptanceFixture의 teardown 메서드에 `pairRoomMemberRepository.deleteAll();`를 추가하니까 에러가 해결되서 해당 변경사항만 push 하겠습니다!

2024-09-22 15:24 UTC, reddevilmidzy commented
어~어이! 실행 순서가 영향을 끼쳤던것일까요...🥹 감사합니당~

2024-09-23 05:29 UTC, koust6u requested changes
안녕하세요. 레디, 잉크 
전반적으로 코드 잘 작성해주셨는데,
테스트가 너무 부족해요 🥲
몇가지 개선할 점이 있어서 RC남겨요

2024-09-23 05:29 UTC, koust6u commented on backend/src/main/java/site/coduo/member/service/MemberService.java
> +    }
[제안]
**제안1. 접근 제한자 조정해주세요. 또는 로직 자체를 사용하는 곳으로 이동해주세요.**
 요 친구 상당히 위험해 보여요. 
반환값으로 Entity인 Member를 그대로 주는데 다른 사람이 해당 메서드를 Controller등 다른 layer에 사용하면 많이 곤란해질거 같습니다. 

**제안2. 테스트 코드 작성해주세요.**

2024-09-23 05:29 UTC, koust6u commented on backend/src/main/java/site/coduo/pairroom/controller/PairRoomController.java
> +        return new PairRoomCreateResponse(pairRoomService.saveNonMemberPairRoom(request));
[제안]
토큰 유무에 따라 처리를 다르게 가져가시는 것 같군요. 
컨트롤러가 해당 로직을 몰라야된다고 봅니다. 
컨트롤러로 서버스 로직의 역할이 침범된거 같아요.
캡슐화주시면 코드가 훨씬 좋아질거같아요.

2024-09-23 05:29 UTC, koust6u commented on backend/src/main/java/site/coduo/pairroom/service/PairRoomService.java
> +    }
[제안]
요친구 테스트 없어요. 🥲

2024-09-23 05:29 UTC, koust6u commented on backend/src/main/java/site/coduo/pairroommember/controller/PairRoomMemberController.java
> +    }
[제안]
이 친구 테스트없어요.🔥

2024-09-23 05:29 UTC, koust6u commented on backend/src/main/java/site/coduo/pairroommember/repository/PairRoomMemberRepository.java
> +    List<PairRoomMemberEntity> findByMember(Member member);
[제안]
요 친구도 테스트가 없어요..
전반적으로 부족한 테스트 채워주세요 😭
 많이 바쁘면 제가 해도되긴하니까 바쁘면 말씀해주세요

2024-09-23 05:29 UTC, koust6u commented on backend/src/test/java/site/coduo/pairroommember/service/PairRoomMemberServiceTest.java
> +
[제안]
**제안1. 중복 코드 개선해주세요**
자주 사용되는 테스트 객체 생성 핼퍼나 유틸을  따로 만드는거 어떨까요?
아니면 별도의 메서드로 추출해주세요.

**제안2. BDD(given-when-then) 스타일 지켜주세요.**

2024-09-23 05:29 UTC, koust6u commented on backend/src/main/java/site/coduo/pairroommember/service/PairRoomMemberService.java
> +        final List<PairRoomMemberEntity> pairRooms = pairRoomMemberRepository.findByMember(member);
[제안]
요친구 실패 케이스 테스트 없어요!!

2024-09-24 01:50 UTC, JiHyeonL approved these changes
제 리뷰 반영해 주신 것 같아 approve 하겠습니다~~!!
수고하셨어용

2024-09-24 02:36 UTC, kelly6bf approved these changes
이미 다른분들이 꼼꼼하게 체크해주셔서 제가 봐드릴게 별로 없네요.. 🥹 남겨드린 리뷰는 향후 개선해도 괜찮아서 전 Approve 드리겠습니당.

2024-09-24 02:36 UTC, kelly6bf commented on backend/src/main/java/site/coduo/pairroom/controller/PairRoomController.java
>          return ResponseEntity.created(URI.create("/"))
나중에 ```/``` 경로에 대한 팀 논의가 필요할거 같아요! HTTP Spec상 Create 응답에 포함되는 경로는 생성된 리소스의 경로이기에 단순히 ```/```로 통일할지 별도의 리소스 경로를 기술할지 컨벤션 정리가 필요할거 같습니다!

2024-09-24 02:36 UTC, kelly6bf commented on backend/src/main/java/site/coduo/pairroommember/service/dto/PairRoomMemberResponse.java
> +        return new PairRoomMemberResponse(pairRoom.getId(), pairRoom.getStatus().name(), pairRoom.getNavigator(),
차라리 ```PairRoomMemberResponse``` 객체에 ```PairRoom```객체를 넘겨서 필요한 값을 스스로 꺼내서 인스턴스를 생성하게 해보는건 어떨까요?

2024-09-24 14:50 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/pairroommember/controller/PairRoomMemberController.java
> +public class PairRoomMemberController {
역시 꼼꼼한 레모네

2024-09-24 14:50 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/pairroommember/controller/PairRoomMemberController.java
> +    public ResponseEntity<List<PairRoomMemberResponse>> getPairRooms(@CookieValue(SIGN_IN_COOKIE_NAME) String token) {
감사합니다ㅏ!

2024-09-24 14:50 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/pairroommember/repository/PairRoomMemberEntity.java
> +    private Member member;
역시 꼼꼼쓰

2024-09-24 14:50 UTC, reddevilmidzy commented on backend/src/test/java/site/coduo/pairroommember/service/PairRoomMemberServiceTest.java
> +
굿굿굿~!!

2024-09-24 14:50 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/member/service/MemberService.java
> +    }
[답변1]
아 이것도 이야기 해보고 싶었는데요, findMemberByCredential() 메서드와 findMemberNameByCredential() 메서드는 사실 token으로 member를 찾고 반환하는 메서드인데 리턴타입만 다른 형태입니다. findMemberByCredential()는 dto를 반환하고 findMemberNameByCredential()는 entity를 반환하는 형태인데요, 만약 entity를 반환하는게 위험하다고 생각하여 dto를 반환하게 된다면 dto가 생길 때마다 메서드 재활용을 하지 못하고 추가해야 합니다 

그래서 메서드 재활용성을 위해 entity를 리턴하는 메서드를 만들자! 해서 memberService에 findMemberByCredential() 메서드를 만든 것이였습니다. 

service 계층에선 dto 반환하는 메서드만 만들지 아니면 entity 반환하는 메서드도 만들지 토론해봐요 :)

[답변2] 
추가해주었습니다!!

2024-09-24 14:50 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/pairroom/controller/PairRoomController.java
> +        return new PairRoomCreateResponse(pairRoomService.saveNonMemberPairRoom(request));
맞아요 토큰이 있을 때에는 자신의 예약 목록 조회를 위해 다른 테이블에도 저장을 가져갑니다.

그래서 컨트롤러에서 유무를 판단했는데, 말씀해주신 문제점이 있었네요!! 
service로 해당 로직을 이동해주었더니 확실히 깔끔해졌네요 (_ _) 👍

2024-09-24 14:50 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/pairroom/service/PairRoomService.java
> +    }
리팩터링 하면서 해당 메서드가 사라져 테스트 추가는 생략하겠습니닷!

2024-09-24 14:50 UTC, reddevilmidzy commented on backend/src/test/java/site/coduo/pairroommember/service/PairRoomMemberServiceTest.java
> +
[제안1] 메서드 분리해주었습니닷!
[제안2] BDD 스타일 놓쳤었네요,,, 보완해주었습니다!!

2024-09-24 14:50 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/pairroommember/service/PairRoomMemberService.java
> +        final List<PairRoomMemberEntity> pairRooms = pairRoomMemberRepository.findByMember(member);
실패 케이스는 멤버 찾기에 실패했을 때에 대한 테스트 말씀하시는건가요오?

2024-09-25 06:04 UTC, koust6u commented on backend/src/main/java/site/coduo/pairroommember/service/PairRoomMemberService.java
> +        final List<PairRoomMemberEntity> pairRooms = pairRoomMemberRepository.findByMember(member);
넵

2024-09-25 06:04 UTC, koust6u approved these changes

2024-09-25 06:06 UTC, merged