[FE] 레퍼런스 링크, 카테고리 리팩토링
woowacourse-teams/2024-coduo pull request #552
Opened 2024-09-23 11:04 UTC by dle234

## 연관된 이슈

- closes: #519 

## 구현한 기능
- api , 카테고리 선택 시 카테고리 Name -> 카테고리 ID 
- 폴더구조 수정 , 커스텀훅 분리
- query , mutation 폴더 분리
- 중복되는 코드 삭제

## 상세 설명
- 폴더구조, 네이밍 변경이 많이 일어났어요 
  - tanstack-query 
    - category ,reference 폴더에 query, muation 파일로 분리하여 저장했습니다.
    - 이 부분에서는 query 를 return 하는 역할만 두도록 했습니다.
  - hooks
    - query, mutation 을 사용하여 특정 기능을 하는 로직들은 커스텀훅으로 분리했습니다. 
    - useCategories, useEditCategory, useReferences 
  - components
 ```
ReferenceCard > AddReferenceForm > CategoryDropdown , AddReferenceForm
              > CategoryManagementModal > CategoriesEditor > CategoryItem > IconButton,ReadonlyCategoryItem
              > Header
              > ReferenceList > Reference
```

- Dropdown 컴포넌트에서 option 으로 value 값만 넘길 수 있어서 {value, id}[] 를 넘겨 사용할 수 있도록 추가해주었습니다.
  - 보여주는 부분에는 value, select 하는 부분에는 id 를 사용합니다.

2024-09-24 08:44 UTC, anttiey requested changes

2024-09-24 08:44 UTC, anttiey commented on frontend/src/components/PairRoom/ReferenceCard/AddReferenceForm/AddReferenceForm.tsx
> +      ></CategoryDropdown>
```suggestion
      <CategoryDropdown
        currentCategoryId={currentCategoryId}
        categories={categories}
        handleCurrentCategory={handleCurrentCategory}
        accessCode={accessCode}
        getCategoryNameById={getCategoryNameById} />
```

2024-09-24 08:44 UTC, anttiey commented on frontend/src/components/PairRoom/ReferenceCard/AddReferenceForm/CategoryDropdown/CategoryDropdown.tsx
> +/* eslint-disable jsx-a11y/no-autofocus */
이 옵션은 무엇인가요?

2024-09-24 08:44 UTC, anttiey commented on frontend/src/components/PairRoom/ReferenceCard/AddReferenceForm/CategoryDropdown/CategoryDropdown.tsx
> +    <>
`Fragment` 없어도 될 거 같네요 😊

2024-09-24 08:44 UTC, anttiey commented on frontend/src/utils/Reference/formatLink.ts
> +    return trimmedLink + '/';
이렇게 반환하면 `http:naver.com` 이 `http:naver.com/` 이 되는 거 아닌가요? 🤔

2024-09-25 01:41 UTC, greetings1012 requested changes
수고하셨습니다!
몇 가지 질문 및 변경 사항 남겼어요 😁

2024-09-25 01:41 UTC, greetings1012 commented on frontend/src/validations/validateCategory.ts
> +const MAX_CATEGORY_LENGTH = 10;
최대 카테고리 갯수인지, 이름 길이인지 조금 불명확할 수 있을 것 같아요!
```suggestion
const MAX_CATEGORY_NAME_LENGTH = 10;
```

2024-09-25 01:41 UTC, greetings1012 commented on frontend/src/utils/Reference/formatLink.ts
> +    return trimmedLink + '/';
`http:naver.com`은 제대로 된 링크가 아닌 것 같아요!
올바른 링크가 아니라고 안내하는 게 좋지 않을까요?

2024-09-25 01:41 UTC, greetings1012 commented on frontend/src/components/common/Dropdown/Dropdown/Dropdown.styles.tsx
> +    font-size: 1.4rem;
font-size에 theme을 사용하지 않은 이유가 있을까요? 🤔

2024-09-26 02:52 UTC, dle234 commented on frontend/src/utils/Reference/formatLink.ts
> +    return trimmedLink + '/';
input 내부에서 사용자에게 보여져야 하는 정보여야 한다고 생각했었는데 보낼때만 붙이면 되겠네요 🥹 수정했습니다!

2024-09-26 02:54 UTC, dle234 commented on frontend/src/components/PairRoom/ReferenceCard/AddReferenceForm/CategoryDropdown/CategoryDropdown.tsx
> +/* eslint-disable jsx-a11y/no-autofocus */
저희 eslint a11y 속성에서 autofocus 를 하지 못하게 되어있더라구요..! input 에서 사용하고 싶어서 주석을 달아줬는데, 이 부분은 좀 더 이야기 해보고 결정하도록 하겠습니다 !

2024-09-26 02:55 UTC, dle234 commented on frontend/src/components/common/Dropdown/Dropdown/Dropdown.styles.tsx
> +    font-size: 1.4rem;
기존에 theme 사용이 안되어있었어서 그냥 그대로 크기만 줄였던 것 같아요..! 수정하겠습니다!

2024-09-26 02:58 UTC, anttiey approved these changes

2024-09-26 02:58 UTC, greetings1012 approved these changes

2024-09-26 02:58 UTC, merged