[BE] 페어 이름으로 액세스코드 생성
woowacourse-teams/2024-coduo pull request #807
Opened 2024-10-16 08:25 UTC by yechop

## 연관된 이슈

- closes: #796 

## 구현한 기능

무작위 형용사 + 드라이버이름 + 받침유무에 따라 와/과 + 무작위 형용사 + 드라이버 이름

## 상세 설명

1. 형용사와 이름 사이에 공백이 없는게 깔끔한듯 하여 공백은 주지 않았습니다.

2. 형용사 목록 enum에서 빼고싶은거나 추가하고싶은 형용사 있으면 얘기해주세요

3. 드라이버 이름이 한글이고 마지막 글자의 받침이 있으면 드라이버 이름 뒤에 "과 ",
이름이 한글인데 마지막 글자에 받침이 없거나 영어나 이모티콘, 특수문자면 “와 “ 로 통일했는데 
영어 이모티콘 특수문자일때 더 좋은 아이디어 있으면 알려주세요
“ and “, “+ “, “ “ 시도해봤으나 별로인듯 합니다

4. 현재 형용사 수가 약 100개입니다
하나의 페어 이름으로 만들수 있는 액세스코드의 경우의 수는 약 10000개정도 됩니다.
만약 10000개의 경우의 수를 꽉 채웠다면 어떻게 처리하는게 좋을까요? 당장은 아무 처리도 하지않아 무한 재귀가 발생합니다
```
private AccessCode generateAccessCode(final String driver, final String navigator) {
        final String generatedAccessCode = AccessCodeGenerator.generate(driver, navigator);
        if (pairRoomRepository.existsByAccessCode(generatedAccessCode)) {
            return generateAccessCode(driver, navigator);
        }
        return new AccessCode(generatedAccessCode);
    }
```

2024-10-16 08:49 UTC, koust6u approved these changes

2024-10-16 08:49 UTC, koust6u commented on backend/src/main/java/site/coduo/pairroom/domain/accesscode/Adjective.java
> +    괜찮은,
헉 ! Enum 사용 굿 !! 근데 형용사 코드 레벨보다 다른 방식으로 외부에서 관리되는 방법도 좋을 거 같아요. 
팀원들의 의견도 궁금하네요.

2024-10-16 08:49 UTC, koust6u commented on backend/src/test/java/site/coduo/pairroom/domain/accesscode/AccessCodeGeneratorTest.java
> +        int postPositionIndex = accessCode.indexOf(driverName) + driverName.length();
사소하지만 final

2024-10-16 08:49 UTC, koust6u commented on backend/src/main/java/site/coduo/pairroom/domain/accesscode/AccessCodeGenerator.java
> +        if (adjective == driverAdjective) {
이거는 == 비교자 의도적 사용이신가요?

2024-10-16 08:49 UTC, koust6u commented on backend/src/main/java/site/coduo/pairroom/domain/accesscode/AccessCodeGenerator.java
> +    private static final int NO_FINAL_CONSONANT = 0;
상수화 굿~~~!!

2024-10-16 08:52 UTC, koust6u commented
> 현재 형용사 수가 약 100개입니다
하나의 페어 이름으로 만들수 있는 액세스코드의 경우의 수는 약 10000개정도 됩니다.
만약 10000개의 경우의 수를 꽉 채웠다면 어떻게 처리하는게 좋을까요? 당장은 아무 처리도 하지않아 무한 재귀가 발생합니다

이 경우는 전에 이야기 한거처럼 #1 #2 이런 식으로 중복 이름에 대한 식별자를 추가하는 건 어떨까요?

2024-10-16 08:57 UTC, yechop commented on backend/src/main/java/site/coduo/pairroom/domain/accesscode/AccessCodeGenerator.java
> +        if (adjective == driverAdjective) {
enum이라 뭘 사용해도 괜찮다고 생각했는데 다른 의견이 있으시면 코멘트 달아주세요!

2024-10-16 10:42 UTC, JiHyeonL requested changes
재미있는 규칙으로 액세스 코드 생성 로직 구현하셨네요!!
수고하셨습니다 👍👍

2024-10-16 10:42 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/pairroom/domain/accesscode/AccessCodeGenerator.java
> +public class AccessCodeGenerator {
`AccessCodeGenerator` 메서드 전체적으로 파라미터에 final이 누락되었어요!

2024-10-16 10:42 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/pairroom/service/PairRoomService.java
>          }
만약 같은 페어(예: 잉크, 프람)가 굉장히 많은 수의 페어룸을 생성한다면, accessCode 생성 시 중복이 발생할 확률이 높아지겠네요.
물론 그럴 가능성은 낮겠지만, 그런 상황이 발생한다면 accessCode를 생성하는데 오랜 시간이 걸릴 것 같아요.

그래서 하나 생각난 아이디어가 있는데요,
중복 발생 시 랜덤 숫자를 accessCode 뒤에 붙여주는 것은 어떨까요?
``` java
    private AccessCode generateAccessCode(final String driver, final String navigator) {
        final String generatedAccessCode = AccessCodeGenerator.generate(driver, navigator);
        if (pairRoomRepository.existsByAccessCode(generatedAccessCode)) {
            // new! accessCode 뒤에 salt 값을 붙이는 메서드. 여기서도 중복이 발생할 가능성이 있기 때문에 재귀문 필요
            return generateAccessCodeWithSalt(driver, navigator);
        }
        return new AccessCode(generatedAccessCode);
    }
```
숫자는 형용사에 비해 중복이 발생할 확률이 낮기 때문에 잉크가 말한 무한 재귀 현상도 해결할 수 있을 것 같아요!

혹시 잉크는 어떻게 생각하시나요?!

2024-10-16 10:42 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/pairroom/domain/accesscode/Adjective.java
> +    괜찮은,
외부에서 관리되는 방법이라 하면 어떤 것을 말씀하시는 걸까요??

2024-10-16 10:43 UTC, koust6u commented on backend/src/main/java/site/coduo/pairroom/domain/accesscode/AccessCodeGenerator.java
> +        if (adjective == driverAdjective) {
아 죄송합니다 enum이었군요 착각했어요

2024-10-16 10:53 UTC, koust6u commented
잉크 질문 추가로 있어서 남겨봐요. 
현재 우리 서비는 페어룸 코드 prefix인 IANxxx 와 IBNxxx 를 패턴 매칭해서 로드밸런서에서 트래픽 분산해주는데, ㅇ사용자가 식별 가능한 이름으로 (prefix 없는 형태로 엑세스 코드가) 바뀌게 된다면 로드 밸런서에서는 어떤 기준으로 트래픽 분산되는지 알고싶어요.!

2024-10-16 10:54 UTC, koust6u commented on backend/src/main/java/site/coduo/pairroom/domain/accesscode/Adjective.java
> +    괜찮은,
음.. 단순하게는 application yml 이나 file 시스템을 생각했는데 오히려 관리가 힘들어 질거같긴하내요 ㅜㅜ

2024-10-16 10:54 UTC, koust6u commented on backend/src/main/java/site/coduo/pairroom/domain/accesscode/Adjective.java
> +    괜찮은,
좋은 아이디어있다면 말씀해주세요 없으면 현행유지 해야할듯하내요

2024-10-16 11:38 UTC, yechop commented on backend/src/main/java/site/coduo/pairroom/service/PairRoomService.java
>          }
좋은 지적입니다!  db조회 후 생성 10000번 시간을 측정해보니 로컬에서도 3초가량 걸리네요.
프람의 #1 #2 아이디어도, 레모네의 랜덤숫자 붙여주기도 해결방안으로 좋다고 생각해요.
하지만 처음 기획 의도인 '액세스코드를 외우기 힘드니 기억하기 쉽게 만들자' 에서 좀 벗어난다고 생각해요.
상황을 공유하고 전체 회의에서 상의해볼까요?

2024-10-16 11:53 UTC, yechop commented
> 잉크 질문 추가로 있어서 남겨봐요. 현재 우리 서비는 페어룸 코드 prefix인 IANxxx 와 IBNxxx 를 패턴 매칭해서 로드밸런서에서 트래픽 분산해주는데, ㅇ사용자가 식별 가능한 이름으로 (prefix 없는 형태로 엑세스 코드가) 바뀌게 된다면 로드 밸런서에서는 어떤 기준으로 트래픽 분산되는지 알고싶어요.!

앗 이 부분을 생각하지 못했네요.. 
무중단배포 어떤식으로 되는지 보고 다시 생각해봐야겠네요

2024-10-16 15:51 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/pairroom/service/PairRoomService.java
>          }
요 부분 해결하고 머지하는게 좋을 것 같네요! 안그러면 병목이 발생할 수도,,

제 의견은 액세스 코드가 중복되도 되는거 아닌가?라는 의견입니다! 

현재는 페어룸에 접근할 때 /pair-room/{access_code} 이런식으로 되어 있고 pair_room 테이블에 액세스 코드가 필드로 있습니다 

근데 이제 만약 /pair-room/{pair_room_id} 이런식으로 액세스 코드 대신 페어룸id로 페어룸으로 접근하고, pair_room 테이블에 액세스 코드 대신 사용자가 지정한 혹은 기억하기 쉬운 코드를 존재하도록한다면, 이제 나의 페어룸 조회할 때 응답으로 이 커스텀된 액세스 코드로 확인하면 되지 않을까요?

2024-10-18 00:54 UTC, JiHyeonL approved these changes

2024-10-22 06:27 UTC, merged