[FE] 🚧 완료 상태 페어룸 1차 구현
woowacourse-teams/2024-coduo pull request #820
Opened 2024-10-17 07:34 UTC by greetings1012

## 연관된 이슈

🚧

## 구현한 기능

완료 상태 페어룸을 1차 구현했습니다. 이후 나오는 api를 확인하고 2차 수정할 예정입니다.

## 상세 설명
🤗

2024-10-17 08:45 UTC, dle234 approved these changes
수고하셨습니당 궁금한거 몇개 질문남겼어요!

2024-10-17 08:45 UTC, dle234 commented on frontend/src/apis/pairRoom.ts
> +    errorMessage: '',
저희 지금 에러 핸들링을 제대로 안 해놔서 에러 메세지가 있는게 좋을 것 같아요!

2024-10-17 08:45 UTC, dle234 commented on frontend/src/components/PairRoom/PairListCard/PairListCard.tsx
> +          <DeleteButton isOpen={isOpen} onClick={() => handleCompletePairRoom(roomCode)} />
페어룸을 종료하는 버튼이라 DeleteButton 네이밍이 적절하지 않은 것 같아요
그리고 PairRoomDeleteModal에도 페어룸을 종료하겠습니까 ? + 페어룸을 종료하면 회고 페이지로 이동합니다. 와 같은 내용이 들어있어도 좋을 것 같아요!

2024-10-17 08:45 UTC, dle234 commented on frontend/src/pages/CompletedPairRoom/CompletedPairRoom.tsx
> +      const { exists } = await getPairRoomExists(accessCode || '');
accessCode 가 없으면 error 페이지로 이동하는데 accessCode || ''로 처리해 준 이유가 있을까요??

2024-10-17 08:45 UTC, dle234 commented on frontend/src/pages/CompletedPairRoom/CompletedPairRoom.tsx
> +  if (isFetching) {
App에서  <Suspense fallback={<Loading />}>
              <CompletedPairRoom />
            </Suspense> 처리를 해 줬는데 로딩처리가 중복된 것 같아요!

2024-10-17 08:45 UTC, dle234 commented on frontend/src/pages/CompletedPairRoom/CompletedPairRoom.tsx
> +      <S.CompletedPairRoomInformationContainer>
👍👍👍👍👍애니메이션 짱이네요

2024-10-17 08:48 UTC, dle234 approved these changes

2024-10-17 08:48 UTC, dle234 commented on frontend/src/pages/CompletedPairRoom/CompletedPairRoom.tsx
> +      const { exists } = await getPairRoomExists(accessCode || '');
추가로 getPairRoomExists 요청 자체가 실패했을때에도 에러처리를 해 주어야 할 것 같습니다! getPairRoomExists 요청이 실패하면 데이터 없는 빈 방에 입장하게 되는 것 같아요.
(근데 이 에러는 추후에 처리해도 좋을 것 같아욥)

2024-10-17 08:57 UTC, greetings1012 commented on frontend/src/apis/pairRoom.ts
> +    errorMessage: '',
추가했습니다!

2024-10-17 09:07 UTC, greetings1012 commented on frontend/src/components/PairRoom/PairListCard/PairListCard.tsx
> +          <DeleteButton isOpen={isOpen} onClick={() => handleCompletePairRoom(roomCode)} />
수정했습니다 👍

2024-10-17 09:17 UTC, greetings1012 commented on frontend/src/pages/CompletedPairRoom/CompletedPairRoom.tsx
> +      const { exists } = await getPairRoomExists(accessCode || '');
> accessCode 가 없으면 error 페이지로 이동하는데 accessCode || ''로 처리해 준 이유가 있을까요??

`const accessCode = useParams().accessCode;` 에서 `accessCode`의 값이 undefined일 수 있어 typescript가 에러를 반환해요 🥲

> 추가로 getPairRoomExists 요청 자체가 실패했을때에도 에러처리를 해 주어야 할 것 같습니다! getPairRoomExists 요청이 실패하면 데이터 없는 빈 방에 입장하게 되는 것 같아요.

요거는 파슬리 코드까지 머지되고 나서 한번에 처리해 주겠습니다!

2024-10-17 09:56 UTC, greetings1012 commented on frontend/src/pages/CompletedPairRoom/CompletedPairRoom.tsx
> +  if (isFetching) {
App의 Suspense를 삭제했습니다!

2024-10-17 12:20 UTC, anttiey requested changes

2024-10-17 12:20 UTC, anttiey commented on frontend/src/App.tsx
> +import CompletedPairRoom from '@/pages/CompletedPairRoom/CompletedPairRoom';
컴포넌트 이름 진짜 스껄하네요 😭

2024-10-17 12:20 UTC, anttiey commented on frontend/src/components/CompletedPairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoryItem/CategoryItem.tsx
> +const CategoryItem = ({ closeModal, categoryName, categoryId, isChecked, handleSelectCategory }: CategoryItemProps) => {
혹시 이렇게 `ReferenceCard` 안에 `CategoryManagementModal` 안에 `CategoriesEditor` 안에 `CategoryItem` 이 있는 이유가 있나요? 컴포넌트 경로가 너무 길어지는 거 같아서요 🤔

2024-10-17 12:20 UTC, anttiey commented on frontend/src/components/CompletedPairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoryItem/CategoryItem.tsx
> +import ReadonlyCategoryItem from '@/components/CompletedPairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoryItem/ReadonlyCategoryItem/ReadonlyCategoryItem';
여기만 봐도...😅

2024-10-17 12:20 UTC, anttiey commented on frontend/src/components/CompletedPairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoryItem/CategoryItem.tsx
> +        <ReadonlyCategoryItem
`ReadonlyCategoryItem` 안의 로직이 그렇게 많지 않아서 따로 컴포넌트로 분리되어 있지 않아도 될 거 같아요. 이 컴포넌트가 따로 도메인 로직이 없어서 껍데기 역할을 하고 있는 거 같습니다!

2024-10-17 12:20 UTC, anttiey commented on frontend/src/components/CompletedPairRoom/ReferenceCard/CategoryManagementModal/CategoryManagementModal.tsx
> +    <Modal isOpen={isOpen} close={closeCategoryManagementModal} size="45rem">
그냥 `closeModal` 을 써도 되지 않나요?

2024-10-17 12:20 UTC, anttiey commented on frontend/src/components/CompletedPairRoom/ReferenceCard/ReferenceCard.tsx
> +          <Header selectedFilteringCategoryName={selectedFilteringCategoryName} onButtonClick={openModal} />
`selectedFilteringCategoryName` 이거 변수명을 줄일 수 있는 방법은 없을까요...

2024-10-17 12:20 UTC, anttiey commented on frontend/src/pages/CompletedPairRoom/CompletedPairRoom.tsx
> +  const accessCode = useParams().accessCode;
```suggestion
  const { accessCode } = useParams()
```

이렇게 쓰는 건 어떤가요?

2024-10-17 12:20 UTC, anttiey commented on frontend/src/pages/CompletedPairRoom/CompletedPairRoom.tsx
> +  const userStatus = useUserStore((state) => state.userStatus);
```suggestion
  const { userStatus } = useUserStore();
```

2024-10-18 01:34 UTC, greetings1012 commented on frontend/src/components/CompletedPairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoryItem/CategoryItem.tsx
> +const CategoryItem = ({ closeModal, categoryName, categoryId, isChecked, handleSelectCategory }: CategoryItemProps) => {
급하게 원래 파일 구조 그대로 따오느라 필요없는 구조가 생겼네요!
CategoriesEditor 단계를 삭제했습니다 👍

2024-10-18 01:38 UTC, greetings1012 commented on frontend/src/components/CompletedPairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoryItem/CategoryItem.tsx
> +        <ReadonlyCategoryItem
여기도 줄였습니다!

2024-10-18 01:43 UTC, greetings1012 commented on frontend/src/components/CompletedPairRoom/ReferenceCard/CategoryManagementModal/CategoryManagementModal.tsx
> +    <Modal isOpen={isOpen} close={closeCategoryManagementModal} size="45rem">
지금 확인해보니 변수명이 중간에 한번 길게 바뀐 부분이 있네요!
수정했습니다

2024-10-18 01:46 UTC, greetings1012 commented on frontend/src/pages/CompletedPairRoom/CompletedPairRoom.tsx
> +  const userStatus = useUserStore((state) => state.userStatus);
수정했습니다!

2024-10-18 01:46 UTC, greetings1012 commented on frontend/src/pages/CompletedPairRoom/CompletedPairRoom.tsx
> +  const accessCode = useParams().accessCode;
수정했습니다!

2024-10-18 01:48 UTC, greetings1012 commented on frontend/src/components/CompletedPairRoom/ReferenceCard/ReferenceCard.tsx
> +          <Header selectedFilteringCategoryName={selectedFilteringCategoryName} onButtonClick={openModal} />
원본 코드와 같은 이름이라 리팩터링할 때 한 번에 고쳐야 할 것 같아요 🥲

2024-10-18 01:54 UTC, anttiey commented on frontend/src/components/CompletedPairRoom/ReferenceCard/ReferenceCard.tsx
> +          <Header selectedFilteringCategoryName={selectedFilteringCategoryName} onButtonClick={openModal} />
코드 다이어트가 시급하군요 ⚠️

2024-10-18 01:58 UTC, anttiey approved these changes

2024-10-18 01:58 UTC, anttiey commented on frontend/src/components/CompletedPairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoryItem/CategoryItem.tsx
> +const CategoryItem = ({ closeModal, categoryName, categoryId, isChecked, handleSelectCategory }: CategoryItemProps) => {
> <img width="267" alt="스크린샷 2024-10-18 오전 10 55 46" src="https://github.com/user-attachments/assets/b54b8e4d-579a-40a6-9341-1d5ce65bcf8d">

폴더 구조가 이렇게 보이는데 안에 `CategoryItem` 만 있어서 혹시 상위에 `CategoriesEditor` 폴더가 있는 거면 제거하고 `CategoryItem` 폴더만 남겨도 될 거 같네요!

2024-10-18 05:21 UTC, merged