[BE] 페어룸 종료 후 회고 작성 기능 API 구현
woowacourse-teams/2024-coduo pull request #821
Opened 2024-10-18 01:25 UTC by kelly6bf

## 연관된 이슈

- closes: #771 

## 구현한 기능
- 회고 작성 API 구현
- 개인 회고 목록 조회 API 구현
- 특정 회고 상세 조회 API 구현
- 특정 회고 삭제 API 구현
- 특정 페어룸에 특정 회원의 회고가 존재하는지 여부 조회 API 구현
- 특정 회원이 특정 페어룸에 존재하는지 여부 조회 API 구현

## 상세 설명
- 회고 기능에 필요한 기능들을 구현함.
- 프론트 요청으로 특정 회원이 특정 페어룸에 아직 참여 상태인지 조회하는 API도 추가로 구현함.

2024-10-18 01:45 UTC, reddevilmidzy requested changes
몇가지 수정했으면 좋겠는 부분 남겼습니다 !

2024-10-18 01:45 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/pairroom/controller/PairRoomController.java
> +            @CookieValue("coduo_whoami") final String credentialToken,
이 값 SIGN_IN_COOKIE_NAME 이 상수 사용해주세요!

2024-10-18 01:45 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/pairroom/service/PairRoomService.java
> +            throw new IllegalArgumentException("페어룸 접근 코드로 null 혹은 빈 값이 입력될 수 없습니다.");
isEmpty() 대신 isBlank()는 어떤가요?

2024-10-18 01:45 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/retrospect/controller/RetrospectController.java
> +            @CookieValue("coduo_whoami") final String credentialToken,
이 클래스에 있는 coduo_whoami 값도 SIGN_IN_COOKIE_NAME 이 상수 사용해주세요!

2024-10-18 01:45 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/retrospect/controller/response/FindRetrospectByIdResponse.java
> +    public static FindRetrospectByIdResponse of(Retrospect retrospect) {
```suggestion
    public static FindRetrospectByIdResponse from(final Retrospect retrospect) {
```

final 누락이 있어요! 그리고 파라미터 값이 하나니까 of 보다 from 이 맞지 않을까요?

2024-10-18 01:45 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/retrospect/repository/RetrospectContentEntity.java
> +    private String content;
500보다 좀 더 넉넉하게 주는 건 어떤가요?

2024-10-18 01:45 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/retrospect/controller/response/FindRetrospectsResponse.java
> +    public static FindRetrospectsResponse of(List<Retrospect> retrospects) {
```suggestion
    public static FindRetrospectsResponse from(final List<Retrospect> retrospects) {
```

2024-10-18 01:45 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/retrospect/domain/Retrospect.java
> +    private final long id;
도메인은 id를 가질 필요가 없지 않나요?!

2024-10-18 01:45 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/retrospect/domain/Retrospect.java
> +    }
이 도메인에서 커스텀 에외를 사용하지 않은 이유가 있으신가요? 
여기서 IllegalArgumentEx를 던지면 common 가서 잡힐 거 같은데, retrospect 도메인의 커스텀 예외와 @RestControllerAdvice를 만들어주세요!

2024-10-18 01:50 UTC, koust6u requested changes
켈리 파일 체인지가 많아 코멘트가 조금있네요.😄
전반적으로 코멘트 확인부탁드립니다.

2024-10-18 01:50 UTC, koust6u commented on backend/src/main/java/site/coduo/retrospect/domain/Retrospect.java
> +    private final long id;
[질문]
도메인인데 ID가 필요한 이유가 뭘까요?

2024-10-18 01:50 UTC, koust6u commented on backend/src/main/java/site/coduo/retrospect/domain/RetrospectContents.java
> +                .toList();
[의견]
개인적으로 단순히 내부 전체를 iterate 하는 경우 Instream보다 for 문이 성능적으로나 가독성 측면에서 더 좋아보이는데 어떻게 생각하시나요?

2024-10-18 01:50 UTC, koust6u commented on backend/src/main/java/site/coduo/retrospect/domain/RetrospectContents.java
> +            throw new IllegalArgumentException("회고 내용 개수는 " + RETROSPECT_CONTENTS_SIZE + "개여야 합니다. - " + values.size());
[제안]
string을 이렇게 concatenate 하는 것보다 .format을 통해 단순화 하는것이 가독성 좋아보입니다.

2024-10-18 01:50 UTC, koust6u commented on backend/src/main/java/site/coduo/retrospect/repository/RetrospectContentEntity.java
> +    @Column(name = "CONTENT", length = 500, nullable = false)
[질문]
회고 내용을 500자로 제안하신 이유가 궁금합니다. 
또 500자로 제안하셨다면, entity보다 domain인 RetrospectContent인 도메인에서도 검증 로직이 필요해보입니다.
이건 비즈니스 규칙에 가깝기 때문에 인프라단의 검증보다 도메인단의 검증이 더 적합하다 느껴요. 

켈리의 의견은 어떠신가요?

2024-10-18 01:50 UTC, koust6u commented on backend/src/main/java/site/coduo/retrospect/repository/RetrospectContentRepository.java
> +    void deleteAllByRetrospect(RetrospectEntity retrospect);
[제안]
전반적으로 JPARepository를 확장한 클래스(인터페이스)들은 테스트가 코드가 없네요. 
추가해주시면 감사하겠습니다

2024-10-18 01:50 UTC, koust6u commented on backend/src/main/java/site/coduo/retrospect/repository/RetrospectEntity.java
> +    }
[질문]
저는 Entity 생성자 파라미터에 ID포함하는 것을 꺼려합니다.
이유는 Entity의 ID는 우리가 관리하는 영역이 아닌 JPA의 관리 대상인데, 불필요하게 열어둬서 다른 개발자가 잘못사용하는 경우가 생길수도 있다고 생각하거든요.

켈리 의견은 어떠신지 궁금합니다.

2024-10-18 01:50 UTC, koust6u commented on backend/src/main/java/site/coduo/retrospect/repository/RetrospectRepository.java
> +    boolean existsByMemberAndPairRoom(Member member, PairRoomEntity pairRoom);
[제안]
이 친구들도 테스트가 없네요. 👀
jpa 쿼리 메서드도 우리가 짠 코드이기 때문에 테스트는 필수라고 생각해요

2024-10-18 01:50 UTC, koust6u commented on backend/src/main/java/site/coduo/retrospect/service/RetrospectService.java
> +        }
[제안]
package site.coduo.pairroom.domain.accesscode;
여기에 AccessCode와 관련된 도메인이 있습니다. 해당 
검증은 Service가 아닌 해당 도메인으로 이전하고 AccessCode 에서 검증하는 것도 괜찮아 보입니다.

2024-10-18 01:50 UTC, koust6u commented on backend/src/main/java/site/coduo/retrospect/service/RetrospectService.java
> +
[제안]
이 친구도 package site.coduo.common.config.web.filter;
여기에 검증 로직이 있습니다. FilterConfig에 해당 URL 등록해서  사용하는 것이 좋아보입니다.
보안 검증을 서비스 계층에서 하는 것보다 Filter에서 하는 것이 더 바람직해보여요. 
coudo_whoami 토큰을 사용하는 다른 엔드포인트들도 마찬가지입니다.

2024-10-18 01:50 UTC, koust6u commented on backend/src/main/java/site/coduo/retrospect/service/RetrospectService.java
> +                        retrospectContent.getAnswer().getValue()))
[제안] 
retrospectContent.getAnswer().getValue()
요 친구 디미터 법칙 지켜지면 좋을거 같아요.

2024-10-18 01:50 UTC, koust6u commented on backend/src/main/java/site/coduo/retrospect/service/RetrospectService.java
> +            throw new IllegalStateException("본인 소유가 아닌 회고는 삭제할 수 없습니다.");
[질문]
저희 컨벤션으로 예외는 CustomException 정의해서 사용하기로 한걸로 알아요.
이 친구만 표준 예외로 던진 이유가 궁금합니다.

2024-10-18 01:50 UTC, koust6u commented on backend/src/test/java/site/coduo/acceptance/PairRoomAcceptanceTest.java
> +        );
[제안]
테스트 코드에서 멤버 생성하는 로직이 전반적으로 중복되어 사용되고 있는데 dummy 생성 helper 클래스를 만들던가 
메서드 추출로 중복을 줄이면  테스트 코드 가독성에 도움될거 같아요!

2024-10-18 02:42 UTC, JiHyeonL requested changes
기능이 꽤 컸는데, 구현하시느라 정말 수고많으셨습니다!
피드백 몇가지 남겼으니 확인 부탁드려요 😀

2024-10-18 02:42 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/retrospect/controller/response/ExistRetrospectWithPairRoomResponse.java
> +package site.coduo.retrospect.controller.response;
컨트롤러에서 쓰이는 `dto`도 전체적으로 문서화 추가해 주세요!

2024-10-18 02:42 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/retrospect/domain/RetrospectContents.java
> +        final List<RetrospectAnswer> retrospectAnswers = answers.stream().map(RetrospectAnswer::new).toList();
두번째 메서드 체이닝부터 개행을 주면 좋을 것 같아요!
```suggestion
        final List<RetrospectAnswer> retrospectAnswers = answers.stream()
        .map(RetrospectAnswer::new)
        .toList();
```

2024-10-18 02:42 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/retrospect/domain/Retrospect.java
> +    }
이 부분 말고도 다른 클래스에서도 `IllegalXXXException`이 사용되고 있는데, 한번 확인해 주시면 좋을 것 같습니다!

2024-10-18 02:42 UTC, JiHyeonL commented on backend/src/test/java/site/coduo/acceptance/AcceptanceFixture.java
> +        retrospectRepository.deleteAll();
👍👍

2024-10-18 02:42 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/pairroom/service/PairRoomService.java
> +                        "입력된 페어룸 접근 코드에 대응되는 페어룸이 존재하지 않습니다. - " + pairRoomAccessCode));
PairRoomRepository에 예외처리된 값을 반환하는
``` java
    default PairRoomEntity fetchByAccessCode(AccessCode accessCode) {
        return findByAccessCode(accessCode.getValue())
                .orElseThrow(() -> new PairRoomNotFoundException("존재하지 않는 페어룸 접근 코드입니다."));
    }
```
이런 메서드가 있어요!
예외를 처리하는 default 메서드가 있는 곳도 있고, 없는 곳도 있어서 헷갈릴 수 있겠네요. 
findXXX의 예외를 서비스단에서 처리할지, 레포지토리에서 처리할지 나중에 같이 이야기 해 봐도 좋을 것 같아요.

2024-10-19 05:26 UTC, kelly6bf commented on backend/src/main/java/site/coduo/pairroom/service/PairRoomService.java
> +            throw new IllegalArgumentException("페어룸 접근 코드로 null 혹은 빈 값이 입력될 수 없습니다.");
실수로 Empty가 들어갔네요..! 변경해볼게요..!

2024-10-19 05:26 UTC, kelly6bf commented on backend/src/main/java/site/coduo/retrospect/controller/response/FindRetrospectByIdResponse.java
> +    public static FindRetrospectByIdResponse of(Retrospect retrospect) {
동의합니다! final 누락과 함께 메서드명도 변경해볼게요.

2024-10-19 05:27 UTC, kelly6bf commented on backend/src/main/java/site/coduo/retrospect/repository/RetrospectContentEntity.java
> +    private String content;
동의합니다. 회고 내용이 포함되니 500은 좀 적네요. 1000정도로 넉넉하게 늘릴게요

2024-10-19 05:30 UTC, kelly6bf commented on backend/src/main/java/site/coduo/retrospect/domain/Retrospect.java
> +    private final long id;
요 며칠 고민해본결과 DB에서 PK로 사용되는 정수값을 도메인이 가질 필요가 없겠구나 생각이 들었습니다! 어떻게보면 도메인이 DB에서 사용되는 개념에 종속되고요.

다만 도메인 특성상 고유값은 필요하다고 생각합니다. 따라서 중복되지 않은 (ex. UUID) 값을 활용해서 도메인을 구별할 수 있는 equals를 재정의 해주려고합니다. 다만 그 값의 필드명은 id(identifier)가 적절하다고 생각이드네용.

2024-10-19 05:30 UTC, kelly6bf commented on backend/src/main/java/site/coduo/retrospect/domain/Retrospect.java
> +    }
바쁘게 개발하다보니 무의식적으로 기본 예외를 사용해버렸습니다..! 전부 커스텀 예외로 변경하겠습니다.

2024-10-19 05:31 UTC, kelly6bf commented on backend/src/main/java/site/coduo/retrospect/domain/Retrospect.java
> +    private final long id;
https://github.com/woowacourse-teams/2024-coduo/pull/821#discussion_r1807190256

이곳에 의견 남겨놨습니다!

2024-10-19 05:31 UTC, kelly6bf commented on backend/src/main/java/site/coduo/retrospect/domain/RetrospectContents.java
> +                .toList();
동의합니다. 현 코드는 for문으로 풀어쓰는게 좀 더 가독성이 높아질거 같아요. 반영해보겠습니다.

2024-10-19 05:32 UTC, kelly6bf commented on backend/src/main/java/site/coduo/retrospect/domain/RetrospectContents.java
> +            throw new IllegalArgumentException("회고 내용 개수는 " + RETROSPECT_CONTENTS_SIZE + "개여야 합니다. - " + values.size());
https://moneylogging.tistory.com/entry/%EC%9E%90%EB%B0%94-%EB%AC%B8%EC%9E%90%EC%97%B4%EC%97%B0%EC%82%B0-%EC%84%B1%EB%8A%A5%EC%B5%9C%EC%A0%81%ED%99%94

성능에도 유리하네요. 예전에 C언로 코딩할때가 생각나서 추억이 드네요. 반영해보겠습니다.

2024-10-19 05:33 UTC, kelly6bf commented on backend/src/main/java/site/coduo/retrospect/repository/RetrospectContentEntity.java
> +    @Column(name = "CONTENT", length = 500, nullable = false)
동의합니다. 도메인 검증은 제가 실수로 누락해버렸네요.

https://github.com/woowacourse-teams/2024-coduo/pull/821#discussion_r1807189942

반영하겠습니다.

2024-10-19 05:40 UTC, kelly6bf commented on backend/src/main/java/site/coduo/retrospect/repository/RetrospectContentRepository.java
> +    void deleteAllByRetrospect(RetrospectEntity retrospect);
개인적으로 `JPARepsitory`를 단순 상속한 인터페이스 테스트 작성이 필요한가라는 의문이 있긴 합니다. 현재 `RetrospectContentRepository` 클래스는 제가 따로 작성한 로직 없이 JPA가 직접 만들어주는 로직으로만 DB접근이 발생하기 때문에 라이브러리의 학습 테스트 느낌으로 다가오는거 같습니다.

그나마 검증할거리는 추상 메서드의 이름을 잘 작성했는가 (id로 멤버를 조회하려면 findById로 잘 적었는가?) 정도인데 이는 이미 Service 테스트가 스프링 부트 테스트로 돌아가기에 실제 JPA와 연동되어 검증이 되어 있기도 하고요.

그래서 현 코드의 테스트는 무엇을 검증하기 위해서인지 잘 와닿지 않습니다. 프람의 의견이 궁금합니다.

2024-10-19 06:22 UTC, kelly6bf commented on backend/src/main/java/site/coduo/retrospect/repository/RetrospectEntity.java
> +    }
무조건 지양하지는 않습니다. 프로젝트 초반 제안드렸던 `Repository`분리 방식을 사용하게되면 직접 id를 포함한 엔티티를 생성해주기 때문에 id를 파라미터에 포함시킵니다. 다만 지금 코드 상황에서 불필요하다는 의견에 동감하기에 제거해보겠습니다.

2024-10-19 06:22 UTC, kelly6bf commented on backend/src/main/java/site/coduo/retrospect/repository/RetrospectRepository.java
> +    boolean existsByMemberAndPairRoom(Member member, PairRoomEntity pairRoom);
https://github.com/woowacourse-teams/2024-coduo/pull/821#discussion_r1807193991

2024-10-19 06:23 UTC, kelly6bf commented on backend/src/main/java/site/coduo/retrospect/service/RetrospectService.java
> +            throw new IllegalStateException("본인 소유가 아닌 회고는 삭제할 수 없습니다.");
https://github.com/woowacourse-teams/2024-coduo/pull/821#discussion_r1807190330

2024-10-19 09:48 UTC, kelly6bf commented on backend/src/main/java/site/coduo/retrospect/domain/RetrospectContents.java
> +            throw new IllegalArgumentException("회고 내용 개수는 " + RETROSPECT_CONTENTS_SIZE + "개여야 합니다. - " + values.size());
지금 변경하기에 생각보다 변경 내용이 커서 따로 리팩토링 PR을 파서 진행하겠습니다.

2024-10-19 09:49 UTC, kelly6bf commented on backend/src/test/java/site/coduo/acceptance/PairRoomAcceptanceTest.java
> +        );
이것도 변경 공수가 너무 커서 일단 선 기능 구현후 따로 리팩토링 PR 파서 적용하겠습니다.

2024-10-19 09:51 UTC, kelly6bf commented on backend/src/main/java/site/coduo/retrospect/domain/RetrospectContents.java
> +        final List<RetrospectAnswer> retrospectAnswers = answers.stream().map(RetrospectAnswer::new).toList();
요게 팀 컨벤션 자동 설정 때문에 계속 아래와 같이 자동으로 변하네요.. 에디터를 손봐야하는데 시간이 좀 걸릴거 같아서 이것도 리팩토링PR에서 적용하겠습니다.

2024-10-19 09:55 UTC, kelly6bf commented
생각보다 리뷰 반영이 오래 걸렸네요. 🙇‍♂️ 모든 리뷰를 반영하기에는 변경 공수가 너무 커서 우선 API Spec과 인프라에 영향을 주는 부분들을 우선적으로 개선하였습니다. 나머지 못한 부분들은 따로 리팩토링 PR을 개설해서 작업하겠습니다.

---
도메인에 포함된 id에 경우는 지금도 고민이 많이 있습니다. 여러 방안을 생각해봤지만 아직 마땅히 떠오르는 부분이 없고, 프론트 API 요구사항 중 id가 포함된 요구 사항이 있어서 이 부분도 따로 리팩토링 PR로 넘겨볼까 합니다. 바쁜 일정이 끝나고 전체적으로 서비스 리팩토링을 하는 시간이 확보되면 꼭 이 주제를 가지고 대화해보고 싶습니다.

감사합니다.

2024-10-19 11:44 UTC, kelly6bf commented
쉬는 시간에 도메인 객체와 id 관련 내용을 찾아보던 여러 아티클중 와닿는게 있어 올려봅니다. (근데 다 우테코 글이네 ;;;)
https://dev-ws.tistory.com/66

2024-10-20 11:08 UTC, JiHyeonL approved these changes

2024-10-21 04:01 UTC, koust6u commented on backend/src/main/java/site/coduo/retrospect/repository/RetrospectContentRepository.java
> +    void deleteAllByRetrospect(RetrospectEntity retrospect);
음.. 저는 쿼리 메서드도 우리가 작성한 코드라고 봐서 테스트 코드를 작성하는 게 맞다고 보긴합니다. 더군다나 쿼리 메서드가 길어지면 길어질수록 검증은 필요하구요. 하지만, 현재 상황에선 켈리 의견도 납득이 갑니다. !! 스타일 차이니 넘어 갑시다!

2024-10-21 04:02 UTC, koust6u approved these changes

2024-10-21 04:09 UTC, reddevilmidzy approved these changes

2024-10-21 04:10 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/retrospect/domain/Retrospect.java
> +    private final long id;
음 아직까지 도메인이 id를 가지고 있어야 하는 이유에 대해 납득이 되진 않는군요, 그러면 엔티티와 완전히 동일해지는 것 같아 둘을 분리한 장점을 취하지 못하는 것 같아요

2024-10-21 04:49 UTC, merged