[FE] 회고 페이지 구현
woowacourse-teams/2024-coduo pull request #828
Opened 2024-10-18 05:23 UTC by dle234

## 연관된 이슈

- closes: #806 

## 구현한 기능
- 회고 생성 폼
- 회고 확인 페이지

## 상세 설명
- Retrospect 페이지는 readonly 라는 props 를 넘길 수 있음
    - retrospect/:retrospectId -> readonly : true → RetrospectView(RetrospectHeader + RetrospectContent)
    - retrospect-> readonly : false → RetrospectForm(RetrospectHeader + RetrospectContent)

### 공통 부분
- 전체 Layout UI
- header UI, header 에 해당 페어룸으로 이동하는 버튼
- 질문UI, 질문에 대한 답변 UI
- 질문 map

### 다른 부분 
- editable
    - 답변 tag : textarea
    - header text
    - 답변 리스트 : 사용자가 작성, 답변 상태 관리
    - 답변 작성 요청 버튼(api post)
    - accessCode 가져오는 방법 : 페어룸 종료 시 location state 에서 가져오기
    - route : /retrospect

- readOnly
    - 답변 tag : pre
    - header text
    - 답변 리스트 : 회고 데이터 api get
    - accessCode 가져오는 방법 : 회고 데이터 get 할때 같이 가져옴
    - route: /retrospect/:retrospectId

### 컴포넌트 설명

- Retrospect 페이지는 Layout UI 제공 + readOnly props 에 따라 다른 렌더링 컴포넌트(공통)
- RetrospectView : api 요청하여 질문에 대한 답변, accessCode 가져옴, header+content 렌더링
- RetrospectForm : location 의 accessCode 받고, useInputAnswer 훅으로 textarea 의 입력 상태, submit 을 관리함. header+content+submit Button 렌더링
- RetrospectContent: 이미 정의되어있는 질문리스트를 map 으로 돌림.(공통)
    - renderAnswer 로 Text, Textarea 를 넘겨줄 수 있음
- RetrospectHeader: Header 에 readOnly 에 따른 text 와 onClick 이벤트 props 생성하여 Header 컴포넌트 렌더링
- Header: header UI(공통)

2024-10-18 11:50 UTC, greetings1012 approved these changes
수고하셨습니다! 몇 가지 궁금한 사항 남겨두었으니 시간날 때 확인해주세요!

2024-10-18 11:50 UTC, greetings1012 commented on frontend/src/App.tsx
> +        },
저희 회고 한번 하면 수정 못하나요...?

2024-10-18 11:50 UTC, greetings1012 commented on frontend/src/components/Retrospect/RetrospectForm/RetrospectForm.tsx
> +  );
컴포넌트로 분리해주세요 🥲

2024-10-18 11:50 UTC, greetings1012 commented on frontend/src/components/Retrospect/RetrospectHeader/RetrospectHeader.tsx
> +          alert('나중에 작성하시겠습니까?');
alert 대신 간단한 모달은 어떤가요?

2024-10-19 09:17 UTC, greetings1012 commented on frontend/src/hooks/Retrospect/const useInputAnswer.ts
파일명에 오류가 있네요!

2024-10-21 04:51 UTC, dle234 commented on frontend/src/App.tsx
> +        },
켈리랑 api 구성할때 필요없다고 생각해서 일단 없이 구현했는데, 추후에 회의때 다시 얘기해볼게요!!

2024-10-21 04:51 UTC, dle234 commented on frontend/src/hooks/Retrospect/const useInputAnswer.ts
와....

2024-10-21 05:44 UTC, anttiey requested changes
안녕하세요, 해시! 회고 페이지 구현 고생 많으셨습니다 🚀
이건 한 가지 제안인데 저만 `Retrospect` 라는 단어를 보면 회고라는 게 바로 떠오르지 않는 걸까요... 물론 해당 단어가 회고를 영어로 풀이한 결과라는 건 알지만 조금 더 친숙하게 `Review` 와 같은 단어를 사용하는 건 어떤지요 🤔

2024-10-21 05:44 UTC, anttiey commented on frontend/src/apis/retrospect.ts
> +export const addRetrospect = async ({ pairRoomAccessCode, answers }: AddRetrospectRequest) => {
다른 곳은 다 `accessCode` 로 되어 있는데 통일하는 건 어떤가요?

2024-10-21 05:44 UTC, anttiey commented on frontend/src/components/Retrospect/RetrospectContent/Question/Question.tsx
> +  children: ReactNode;
`React.PropsWithChildren` 쓰는 건 어떤가요?

2024-10-21 05:44 UTC, anttiey commented on frontend/src/components/Retrospect/RetrospectView/RetrospectView.tsx
> +  const retrospectId = params.retrospectId || '';
```suggestion
  const { retrospectId } = useParams();
```

이렇게 쓰는 건 어떤가요?

2024-10-21 05:44 UTC, anttiey commented on frontend/src/components/Retrospect/RetrospectContent/RetrospectContent.tsx
> +  renderAnswer: (index: number, id: string) => React.ReactNode;
이렇게 함수를 통해 컴포넌트를 렌더링하게 되면 문제가 생길 여지가 아주 많답니다. (제가 레벨2 미션을 진행하면서 대표적으로 리뷰어에게 지적을 받았던 부분이에요 🥲)

리뷰어가 주셨던 답변 인용해 봅니다!

> 네 맞습니다 파슬리! 매번 새로 생성 되기 때문에 React의 diff 알고리즘 성능이 저하되는 문제가 있고, 예상치 못한 동작을 유발할 수 있기 때문에 지양됩니다!

2024-10-21 05:44 UTC, anttiey commented on frontend/src/components/Retrospect/RetrospectHeader/RetrospectHeader.tsx
> +  const getHeaderProps = (isReadOnly: boolean) => {
`readOnly` 와 `isReadOnly` 에 차이를 둔 이유가 있나요? 둘 다 boolean 값을 가지고 있는 거 같아서요!

2024-10-21 05:44 UTC, anttiey commented on frontend/src/components/Retrospect/retrospect.type.ts
> +export interface RetrospectQuestion {
`Retrospect` 폴더에 귀속되는 타입이므로 `Retrospect.type.ts` 로 파일 이름을 변경해 주세요 😊

2024-10-21 05:44 UTC, anttiey commented on frontend/src/hooks/Retrospect/const useInputAnswer.ts
> +    await mutateAsync({ pairRoomAccessCode, answers }).then(() => navigate(`/room/${pairRoomAccessCode}/completed`));
여기 `mutateAsync` 를 사용한 이유가 있나요?

2024-10-21 07:46 UTC, dle234 commented on frontend/src/components/Retrospect/RetrospectHeader/RetrospectHeader.tsx
> +  const getHeaderProps = (isReadOnly: boolean) => {
앗 그러네요! 수정하겠습니다

2024-10-21 07:52 UTC, dle234 commented on frontend/src/apis/retrospect.ts
> +export const addRetrospect = async ({ pairRoomAccessCode, answers }: AddRetrospectRequest) => {
앗 그렇네요 !! 수정하겠습니다!

2024-10-21 07:54 UTC, dle234 commented on frontend/src/components/Retrospect/RetrospectContent/RetrospectContent.tsx
> +  renderAnswer: (index: number, id: string) => React.ReactNode;
렌더링이 추가로 된다고 해도 그정도의 렌더링은 성능 상 크게 문제가 되지 않을 것 같다고 생각했었는데, 괜히 위험을 심어두기보다 로직을 수정하는게 더 나을 것 같네요 !

2024-10-21 07:58 UTC, dle234 commented on frontend/src/hooks/Retrospect/const useInputAnswer.ts
> +    await mutateAsync({ pairRoomAccessCode, answers }).then(() => navigate(`/room/${pairRoomAccessCode}/completed`));
전역으로 에러 처리를 하고 있기도 하고, 성공상태가 단순한 navigate 라 onSuccess 로 크게 분리 할 필요 없이 .then 으로 하는게 더 알아보기 쉬울 것 같다고 생각했어요 ..!

2024-10-21 10:33 UTC, dle234 reviewed
구조 수정된 부분입니다!!

```js
 <S.LayoutForm onSubmit={handleSubmit}>
        {RETROSPECT_QUESTIONS.map((question, index) => (
          <Question key={question.id} id={question.id} question={question.value}>
            <S.Textarea
              key={question.id}
              placeholder="질문에 대한 답변을 작성해주세요."
              id={question.id}
              value={answers[index]}
              onChange={(event) => handleChange(index, event.target.value)}
            />
          </Question>
        ))}

        <Button disabled={hasEmptyField()} type="submit" css={S.SubmitButton}>
          작성 완료
        </Button>
      </S.LayoutForm>

```
함수로 jsx 를 넘기지 않고,  내부에서 children 으로 넣어주었습니다! 그리고 RetrospectContent 삭제했습니다!

2024-10-21 10:53 UTC, anttiey approved these changes

2024-10-21 10:54 UTC, merged