[FE] Input 컴포넌트 리팩터링
woowacourse-teams/2024-coduo pull request #946
Opened 2024-11-03 16:12 UTC by dle234

## 연관된 이슈

- closes: #932 

## 구현한 기능

## 상세 설명

2024-11-05 06:48 UTC, greetings1012 requested changes
수고하셨습니다! 
수정 사항 남겨놓았으니, 시간날 때 확인해주세요~

2024-11-05 06:48 UTC, greetings1012 commented on frontend/src/components/PairRoom/CategoryManagementModal/CategoryItem/CategoryItem.styles.ts
> +export const Form = styled.form`
```suggestion
export const Layout = styled.form`
```

2024-11-05 06:48 UTC, greetings1012 commented on frontend/src/components/_common/InputGroup/Input/Input.tsx
> +  focusColor?: string;
여기서 hex값보다는 theme.color를 받는 게 더 좋을 것 같아요!

2024-11-05 06:51 UTC, anttiey requested changes

2024-11-05 06:51 UTC, anttiey commented on frontend/src/components/_common/InputGroup/Message/Message.tsx
> +  children,
```suggestion
  $css,
  status = 'DEFAULT',
  fontSize = theme.fontSize.sm,
  children,
```

`props` 와 정렬 순서가 같았으면 좋겠어요!

2024-11-05 06:51 UTC, anttiey commented on frontend/src/components/_common/InputGroup/Input/Input.tsx
> +  onReset?: () => void;
```suggestion
  $css?: ReturnType<typeof css>;
  status?: InputStatus;
  width?: string;
  height?: string;
  borderRadius?: string;
  focusColor?: string;
  onReset?: () => void;
```

`$css` 가 가장 위로 올라갔으면 좋겠어요! (가독성 문제)

2024-11-05 06:51 UTC, anttiey commented on frontend/src/components/_common/InputGroup/Input/Input.tsx
> +const Input = forwardRef<HTMLInputElement, InputProps>(
저희 `forwardRef` 제거하기로 했으니 제거합시다!

2024-11-05 06:51 UTC, anttiey commented on frontend/src/components/_common/InputGroup/Input/Input.tsx
> +        $focusColor={focusColor}
그냥 `color` 로 받아도 되지 않을까요?

2024-11-13 03:04 UTC, dle234 commented on frontend/src/components/PairRoom/CategoryManagementModal/CategoryItem/CategoryItem.styles.ts
> +export const Form = styled.form`
아래 보시면 Layout 이 이미 있어요! 편집중 일때의 layout 과 편집중이 아닐때의 layout 이 스타일은 공통이어야 하는데, 편집중일때는 form으로도 감싸야해서 네이밍이 조금 애매해진 것 같네요 ㅠ
(편집중일때와 편집중이 아닐때의 컴포넌트를 분리하지 않은 이유는 useEditCategory 훅을 보시면 두 컴포넌트의 기능들이 서로 연관이 되어있어서 분리하기 어렵더라구요..)
일단 LayoutForm 으로 수정할게요!

2024-11-13 03:08 UTC, dle234 commented on frontend/src/components/_common/InputGroup/Input/Input.tsx
> +  focusColor?: string;
👍👍

2024-11-13 03:13 UTC, dle234 commented on frontend/src/components/_common/InputGroup/Input/Input.tsx
> +        $focusColor={focusColor}
color 로 하면 Input 선 색이랑 헷갈릴수도 있을 것 같아서 focusColor 라고 했는데 color 가 더 알아보기 쉬울까요??

2024-11-13 05:24 UTC, anttiey commented on frontend/src/components/_common/InputGroup/Input/Input.tsx
> +        $focusColor={focusColor}
`Dropdown` 도 그냥 `color` 로만 받고 있어서 둘을 맞추면 좋을 것 같네요!

2024-11-13 05:26 UTC, greetings1012 approved these changes

2024-11-13 05:31 UTC, dle234 commented on frontend/src/components/_common/InputGroup/Input/Input.tsx
> +        $focusColor={focusColor}
오 dropdown 쓰면서 불편함을 못느꼈어서 color 로 하는게 좋을 것 같네요!!

2024-11-13 10:07 UTC, greetings1012 approved these changes

2024-11-13 13:07 UTC, anttiey approved these changes

2024-11-14 05:57 UTC, merged