[BE] 멤버 도메인 미사용 컬럼 삭제 및 필드명 통일
woowacourse-teams/2024-coduo pull request #956
Opened 2024-11-07 06:04 UTC by koust6u

## 연관된 이슈

- closes: #952 

## 구현한 기능
1. 미사용 profileImage 컬럼 삭제
2. 깃허브 측에서 받는 데이터는 Provider 접두사 붙힘
3. Member 도메인 테스트 더미 값 test/java/src/~~/ member/support 패키지에 묵어둠  

## 상세 설명
테스트 총 실행 시간: 13초 388
<img width="1595" alt="image" src="https://github.com/user-attachments/assets/bbe832be-f4fd-42b7-8314-183ea909e91d">
에서 
<img width="1309" alt="image" src="https://github.com/user-attachments/assets/ee67cc30-2f05-41de-aa69-cde3faf09077">
7초 536으로 개선

1. 레퍼런스 생성 시 Jsoup으로 실제 Html 호출을 Fake객체로 테스팅 시 호출 막음. 5초 가량 개선
2.SSE (이젠 안쓰이겠지만.. ) Fake 객체 Timeout Duration 500ms -> 1ms으로 변경. 2초가량 개선

2024-11-07 06:13 UTC, yechop approved these changes

2024-11-07 06:13 UTC, yechop commented on backend/src/test/java/site/coduo/member/support/MemberDummy.java
> +public abstract class MemberDummy {
좋네요
그럼 다른 fixture 들도 이런 방식으로 바꾸는게 좋을까요?

2024-11-07 06:16 UTC, koust6u commented on backend/src/test/java/site/coduo/member/support/MemberDummy.java
> +public abstract class MemberDummy {
일단 테스트 코드 제가 담당하기로 해서 만약 member같이 중복되는 fixture들이 많으면 제가 최대한 수정해보겠습니다!

2024-11-07 06:21 UTC, reddevilmidzy requested changes
멤버 관련 리팩터링은 브랜치 member-refactor 에서 한번에 모아서 dev로 가시려는거죠?

2024-11-07 06:21 UTC, reddevilmidzy commented on backend/src/test/java/site/coduo/member/support/MemberDummy.java
캬 좋습니다 테스트 코드가 한층 더 깔꼼해졌네요 

한가지 고민은 몇가지 fixture가 있는데 요 놈들은 test 패키지 하단에 fixture 패키지에 모여있습니다. MemberDummy 클래스는 이 fixture들과는 살짝 성격이 다른 거 같긴(fixture들은 상수 모아둠, memberdummy는 뭔가 메이커 느낌) 하지만 이렇게 패키지 구조를 가져가신 이유가 있으실까요?!

2024-11-07 06:21 UTC, reddevilmidzy commented on backend/src/test/java/site/coduo/pairroom/service/PairRoomServiceTest.java
요 클래스 자동 정렬 단축키 한번 해주세욥!

2024-11-07 06:32 UTC, koust6u commented on backend/src/test/java/site/coduo/member/support/MemberDummy.java
> 멤버 관련 리팩터링은 브랜치 member-refactor 에서 한번에 모아서 dev로 가시려는거죠?

네 맞습니다.

>한가지 고민은 몇가지 fixture가 있는데 요 놈들은 test 패키지 하단에 fixture 패키지에 모여있습니다. MemberDummy 클래스는 이 fixture들과는 살짝 성격이 다른 거 같긴(fixture들은 상수 모아둠, memberdummy는 뭔가 메이커 느낌) 하지만 이렇게 패키지 구조를 가져가신 이유가 있으실까요?!

우선 fixture package를 보지 못했어요. fixture 패키지로 이동 시켜도  큰 문제 없을 거 같아요.

2024-11-07 06:43 UTC, JiHyeonL reviewed
오우 수고하셨습니다 👍

2024-11-07 06:43 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/member/domain/Member.java
> +                   final LocalDateTime deletedAt) {
요기도 마지막 파라미터 다음 엔터 한번 쳐주세욥

2024-11-07 06:43 UTC, JiHyeonL commented on backend/src/test/java/site/coduo/fixture/MemberDummy.java
> +public abstract class MemberDummy {
👏👏

2025-01-07 05:08 UTC, reddevilmidzy approved these changes
👍

2025-01-07 05:08 UTC, merged