[FE] IconButton 구현
woowacourse-teams/2024-coduo pull request #957
Opened 2024-11-07 12:05 UTC by greetings1012

## 연관된 이슈

- closes: #942 

## 구현한 기능

IconButton을 구현했습니다.

## 상세 설명

IconButton을 만들어 각 아이콘 버튼에 적용했습니다.

```tsx
interface IconButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  $css?: ReturnType<typeof css>;
  icon: React.ReactElement<React.JSXElementConstructor<IconType | SVGElement>>;
  size?: 'sm' | 'md' | 'lg' | 'xl' | string;
  width?: string;
  isActive?: boolean;
  onClick?: () => void;
}
```

color 등 아이콘에 대한 상세 디자인은 따로 수정해 icon에 적용하면 됩니다.
그냥 icon을 children으로 받으면 color 속성을 따로 받아 넣어주기가 어렵더라구요 🥲

2024-11-13 05:49 UTC, anttiey requested changes

2024-11-13 05:49 UTC, anttiey commented on frontend/src/components/_common/Button/IconButton/IconButton.tsx
> +  width?: string;
혹시 `size` 에서 받는 문자열과 `width` 에서 받는 문자열의 차이가 있나요? (`width` 는 있는데 `height` 는 없는 이유도 궁금합니다!)

2024-11-13 05:49 UTC, anttiey commented on frontend/src/components/_common/Button/IconButton/IconButton.tsx
> +  onClick?: () => void;
`React.ButtonHTMLAttributes<HTMLButtonElement>` 이거 `extends` 하면 자동적으로 `onClick` 이 포함되어서 별도로 선언하지 않아도 사용할 수 있지 않나요?

2024-11-13 05:49 UTC, anttiey commented on frontend/src/components/_common/Modal/CloseButton/CloseButton.styles.ts
> +export const button = css`
여기 다른 변수들과의 통일성을 위해 `buttonStyles` 라고 바꿔 주실 수 있을까요?

2024-11-13 05:49 UTC, anttiey commented on frontend/src/components/PairRoom/CategoryManagementModal/CategoryItem/CategoryItem.styles.ts
> +`;
아이콘 색상을 사용처에서 CSS로 지정해서 주는 것 보다는 `IconButton` 안에 아이콘의 색상을 조절하는 `props` 도 있으면 좋을 거 같아요! 아이콘 색상은 자주 조절하게 될 거 같아서요 😎

2024-11-13 05:49 UTC, anttiey commented on frontend/src/components/_common/Button/IconButton/IconButton.tsx
> +const IconButton = ({ icon, size = 'sm', width, isActive = true, $css, onClick, ...props }: IconButtonProps) => {
`backgroundColor` 조절하는 `props` 도 있으면 좋을 거 같아요 🙌🏻

2024-11-13 07:36 UTC, greetings1012 commented on frontend/src/components/_common/Button/IconButton/IconButton.tsx
> +  width?: string;
width는 필요 없는 prop이었네요! 제거했습니다 🔥
size에 `5rem`의 식으로 넣으면 자동으로 사이즈가 결정됩니다 😁

2024-11-13 07:37 UTC, greetings1012 commented on frontend/src/components/_common/Button/IconButton/IconButton.tsx
> +  onClick?: () => void;
모달에서 사용할 때 해시가 `event.stopPropagation();`이 필요하다고 해서 이 부분을 오버라이드 하기 위해 별도로 지정해 주었습니다 😁

2024-11-13 07:39 UTC, anttiey commented on frontend/src/components/_common/Button/IconButton/IconButton.tsx
> +  onClick?: () => void;
그렇다면 기본 `onClick` 타입을 사용하고 모달에서 함수를 전달할 때 `event.stopPropagation()` 를 추가해 주는 게 더 좋을 거 같아요! 다른 사용처에서는 위 구문이 필요하지 않을 거 같아서요 🧐

2024-11-13 07:39 UTC, greetings1012 commented on frontend/src/components/_common/Modal/CloseButton/CloseButton.styles.ts
> +export const button = css`
수정했습니다 👍

2024-11-13 07:45 UTC, greetings1012 commented on frontend/src/components/PairRoom/CategoryManagementModal/CategoryItem/CategoryItem.styles.ts
> +`;
저도 따로 아이콘 색상 prop을 뚫어주려고 했는데... children을 받아 넣어주는 구조로는 색을 따로 지정해줄 방법이 없더라구요 🥲
혹시 좋은 방법이 있을까요?

2024-11-13 07:51 UTC, anttiey commented on frontend/src/components/PairRoom/CategoryManagementModal/CategoryItem/CategoryItem.styles.ts
> +`;
> IconButton.styles.ts
```js
export const Layout = styled.button<{ $iconColor: string }>`
  display: flex;
  justify-content: center;
  align-items: center;

  width: 3rem;
  height: 3rem;
  padding: 0.5rem;
  border-radius: 0.3rem;

  color: ${({ theme }) => theme.color.primary[800]};
  font-size: ${({ theme }) => theme.fontSize.base};

  transition: all 0.3s;

  cursor: pointer;

  &:hover {
    background-color: ${({ theme }) => theme.color.black[300]};
    color: ${({ theme }) => theme.color.primary[900]};
  }

  svg {
    color: ${({ $iconColor }) => $iconColor};
  }
`;
```

혹시 이런 식으로 색상을 변경해 줄 수는 없나요?

2024-11-13 08:08 UTC, greetings1012 commented on frontend/src/components/_common/Button/IconButton/IconButton.tsx
> +const IconButton = ({ icon, size = 'sm', width, isActive = true, $css, onClick, ...props }: IconButtonProps) => {
이제 IconButton도 Button처럼 theme에 존재하는 색 혹은 hex 색상 코드를 받아 자동으로 hover, active를 계산합니다!

2024-11-13 08:21 UTC, greetings1012 commented on frontend/src/components/PairRoom/CategoryManagementModal/CategoryItem/CategoryItem.styles.ts
> +`;
그 방식으로 시도해봤는데 정상적으로 동작하지 않더라구요!
대신, 조금 더 찾아보니 아래와 같은 방법이 있었어요.
```
      {React.cloneElement(icon as React.ReactElement, { style: { color } })}

```

이제 color props를 통해 icon의 색을 지정해 줄 수 있습니다!

2024-11-13 12:59 UTC, anttiey commented on frontend/src/components/PairRoom/CategoryManagementModal/CategoryItem/CategoryItem.styles.ts
> +`;
어떤 경우에서 정상적으로 동작하지 않았는지 들어 볼 수 있을까요? 제가 브랜치 받아서 작업했을 때는 위 방법으로 색상이 바꼈거든요 🥲 해당 코드는 강제 형변환을 하고 있어서 안전하지 않을 거 같아요.

2024-11-13 13:01 UTC, anttiey commented on frontend/src/components/_common/Button/IconButton/IconButton.tsx
> +import React from 'react';
그리고 추가적으로 `IconButton` 컴포넌트가 `Button` 과는 다른 별도의 컴포넌트라서, 아예 `Button` 폴더 밖으로 나와 있는 게 좋을 거 같아요!

2024-11-15 11:06 UTC, greetings1012 commented on frontend/src/components/PairRoom/CategoryManagementModal/CategoryItem/CategoryItem.styles.ts
> +`;
지금 리팩터링 해보니 disabled 로직을 처리하는 과정에서 코드가 꼬여 정상적으로 동작하지 않는 것처럼 보였네요!
color props 관련 로직을 다시 리팩터링했습니다 👍

2024-11-15 11:06 UTC, greetings1012 commented on frontend/src/components/_common/Button/IconButton/IconButton.tsx
> +import React from 'react';
폴더 구조 수정했습니다!

2024-11-15 16:01 UTC, dle234 approved these changes
늦게 봐서 죄송합니다🥹

2024-11-15 16:01 UTC, dle234 commented on frontend/src/utils/calculateButtonColor.ts
> +const clamp = (value: number, min: number, max: number) => Math.min(Math.max(value, min), max);
이 계산은 혹시 어떤걸 의미하나요?

2024-11-18 05:17 UTC, greetings1012 commented on frontend/src/utils/calculateButtonColor.ts
> +const clamp = (value: number, min: number, max: number) => Math.min(Math.max(value, min), max);
색상 코드를 10진법으로 바꾼 숫자가 max와 min 사이를 벗어나지 않도록 합니다!(혹시 모를 오버플로우, 언더플로우 방지용)

2024-11-18 05:20 UTC, anttiey approved these changes

2024-11-18 05:34 UTC, merged