[BE] SSE 기반 타이머 잔여 시간 조회 기능을 Web Socket 기반으로 변경
woowacourse-teams/2024-coduo pull request #966
Opened 2024-11-20 06:33 UTC by kelly6bf

## 연관된 이슈

- closes: #961 

## 구현한 기능
- 기존 SSE 로직을 Web Socket으로 변경

## 상세 설명
- 아직 테스트가 부족해 테스트 서버에만 배포해 기능 연결 확인 후 개선하겠습니다.

2024-11-20 06:42 UTC, yechop commented on backend/src/main/java/site/coduo/websocket/exception/EmptyQueryException.java
> +    public EmptyQueryException(String message) {
예외 클래스들에 final

2024-11-20 07:11 UTC, reddevilmidzy requested changes
수고 많으셨습니다!
사소한 코멘트랑 질문 남겼어요

2024-11-20 07:11 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/websocket/message/EventAndDataMessage.java
> +}
WebSocketMessage 를 인터페이스로 두고 이 EventAndDataMessage를 레코드로 설계하신 이유가 궁금합니다!

2024-11-20 07:11 UTC, reddevilmidzy commented on backend/src/test/java/site/coduo/websocket/QueryAccessCodeParserTest.java
> +        String query = "user=ink&accesscode=";
요오기 final ... !

2024-11-21 08:21 UTC, yechop approved these changes

2024-11-21 08:34 UTC, yechop commented on backend/src/main/java/site/coduo/websocket/message/EventAndDataMessage.java
> +}
WebSocketMessage는 타이머, 레퍼런스 링크, 투두 에서 사용될 예정입니다.
현재 타이머엔 event와 data 만 필요하지만 도메인이나 상황에 따라 다양한 필드를 가진 WebSocketMessage들이 필요할 수 있어 추상화 했습니다.

2024-11-23 03:29 UTC, JiHyeonL approved these changes

2024-11-23 04:56 UTC, reddevilmidzy commented on backend/src/main/java/site/coduo/websocket/message/EventAndDataMessage.java
> +}
아하 인터페이스를 레코드로 구현하는게 신기(?)해서 남긴 질문이였어요

지금 인터페이스는 뭔가 데이터 모음을 한번에 처리하기 위한 그런 역할이군요

2024-11-23 04:56 UTC, reddevilmidzy approved these changes

2024-11-23 06:15 UTC, merged