[BE] [BE] 기존 SSE 코드 완전 제거 및 타이머 동기화 기능을 웹소켓으로 변경 작업 마무리
woowacourse-teams/2024-coduo pull request #985
Opened 2024-12-17 05:04 UTC by kelly6bf

## 연관된 이슈

- closes: #983 

## 구현한 기능
- 타이머 잔여시간 조회 기능에 Web Socket 적용
- 기존 SSE 코드 제거

## 상세 설명
- 타이머 잔여시간 조회 기능에 Web Socket을 적용하고 기존 SSE 로직을 제거하였습니다.
- 테스트 코드가 아직 미완성입니다. 이는 향후 예정된 대규모 테스트 개선 작업에서 함께 논의해봅시다.

2024-12-17 05:08 UTC, yechop approved these changes

2024-12-17 06:17 UTC, JiHyeonL approved these changes
웹소켓 어떻게 사용하셨는지 궁금해서 브랜치 pull 받아서 코드 쭉 살펴봤는데 정말 깔끔하게 잘 구현하셨더라구요. 대단해요 👍👍 
수고 많으셨습니다!!

2024-12-17 06:17 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/websocket/WebSocketHandler.java
> +        pairRoomWebSocketSessionStore.removeSession(pairRoomAccessCode, session);
페어룸에 있는 사용자가 한 명 나갔을 경우, 이 메서드가 실행되어 세션이 삭제되는 방식이 맞을까요??
신기하네요!!😀

2024-12-17 08:53 UTC, kelly6bf commented on backend/src/main/java/site/coduo/websocket/WebSocketHandler.java
> +        pairRoomWebSocketSessionStore.removeSession(pairRoomAccessCode, session);
맞습니다!! 웹소켓 연결이 끊어질경우 실행되는 후처리 함수에서 직접 정의한 세션을 삭제합니다!

아 근데.. 이거 이방식이면 SSE 처럼 프로덕션 A, B로 분리되면 유지가 안되네요..

2024-12-17 09:00 UTC, JiHyeonL commented on backend/src/main/java/site/coduo/websocket/WebSocketHandler.java
> +        pairRoomWebSocketSessionStore.removeSession(pairRoomAccessCode, session);
sse 쓸 때도 커넥션 저장하는 용도의 스토리지가 있었는데, 웹소켓은 `PairRoomWebSocketSessionStore` 이 친구가 그 역할을 하고 있는 것 같더라구요. 레디스 써야겠네요😅

2024-12-17 15:10 UTC, reddevilmidzy requested changes
수고 많으셨습니당!

2024-12-17 15:10 UTC, reddevilmidzy commented on backend/src/test/java/site/coduo/sync/service/EventStreamsRegistryTest.java
> +//class EventStreamsRegistryTest {
윽 테스트 코드 다 주석처리 해두면 나중에 봤을 때 이 친구를 왜 주석처리 했는지 확인하기 어려울 것 같아요,,,ㅠ
todo 주석을 추가하여 추후에 어떻게 처리해야할지를 남겨보는건 어떤가요

2024-12-18 05:08 UTC, kelly6bf commented on backend/src/test/java/site/coduo/sync/service/EventStreamsRegistryTest.java
> +//class EventStreamsRegistryTest {
필요없는 테스트를 아예 제거했습니다! 웹소켓의 어떤 부분을 검증해볼지 다함께 의논하고 테스트를 작성해보면 좋을거 같습니다!

2024-12-19 05:15 UTC, reddevilmidzy approved these changes
테스트도 나중에 추가 부탁드립니다ㅏ

2024-12-19 07:36 UTC, merged